### ISSUE TITLE
How do I transfer vtho to  another wallet or exchange.

### ISSUE THREAD

**Issue by VthorsHammer** [vechain/thor-sync.electron#307]
Currently using VeChain Sync v1.0.4.  I have over 10000 vtho in this wallet and would like to send it to another wallet.  VeChain Sync v1.0.4 has a transfer vet function  but no transfer vtho function.  Any help would be appreciated.
![snap319](https://user-images.githubusercontent.com/48582336/54415579-048e7700-46d3-11e9-9f8c-4b94317a7e7a.jpg)

**Comment by AsbertMa** [comment]
Try this.
https://laalaguer.github.io/vechain-token-transfer/

**Comment by VthorsHammer** [comment]
AsbertMa,  Worked like a charm. Thank You for your help.
