### ISSUE TITLE
Ron Wehler

### ISSUE THREAD

**Issue by wehlerrj** [vechain/thor-sync.electron#338]
Hi when I open my vchain acc it will not ask me for my  un or pasword it just opens my acc. can you please help thank you Ron W

**Comment by XJWX89** [comment]
hi @wehlerrj , I’m not sure I get your meaning...Would you mind explaining what you mean?  (e.g. whats un? what do you need for help?）

**Comment by wehlerrj** [comment]
Hi it will not ask me for user name or pass word it just go to my account. Thank you Ron W 

In a message dated 6/4/2019 11:49:05 AM Eastern Standard Time, notifications@github.com writes:

hi @wehlerrj , I’m not sure I get your meaning...Would you mind explaining what you mean?  (e.g. whats un? what do you need for help?）

**Comment by XJWX89** [comment]
Hi @wehlerrj , its delicate behavior, the wallet address is your identity; therefore, there is no username. On the other hand, when you create /import your wallet, it asks you to input the password for signing a transaction or certificate.

**Comment by wehlerrj** [comment]
Ok thank you and have a great day.

In a message dated 6/4/2019 11:11:52 PM Eastern Standard Time, notifications@github.com writes:

Hi @wehlerrj , its delicate behavior, the wallet address is your identity; therefore, there is no username. On the other hand, when you create /import your wallet, it asks you to input the password for signing a transaction or certificate.

**Comment by XJWX89** [comment]
Please always remember to [keep your wallet safe](https://github.com/vechain/thor-sync.electron/wiki/Wallet#keep-your-wallet-safe). if you have further question feel free to reopen an issue. have a good day!
