### ISSUE TITLE
Wallets spontaneously disappear.

### ISSUE THREAD

**Issue by kennethhoytwoodruff** [vechain/thor-sync.electron#340]
**Describe the bug**
Sometimes I open Sync and the wallets that I previously imported/created are not there.  I then have to re-import the wallets.  This has happened to me on both main and test net.

**To Reproduce**
Steps to reproduce the behavior (this is very difficult to reproduce):
1. Import/Create a wallet.
2. Close Sync.
3. Open Sync.
4. Click on Wallets.
5. Wallets are gone.

**Expected result:**
Expect to see wallets when opening Sync

**Desktop OS :**
MacOS 10.12.6

**Sync Version:**

Sync: v1.0.8
Connex:  1.2.3
Electron:  3.0.16
Chrome:  66.0.3359.181
V8:  6.6.346.32

**Additional context**
Very difficult to reproduce.

**Comment by XJWX89** [comment]
hi @kennethhoytwoodruff , thanks for issue . here are some questions need your help to investigate this issue:
1. when you import/create a wallet, did you see the wallet appear in wallet list?
2. did you clear the db or manually delete from the local db （toggle dev tool -> application /storage)
3. do all the wallets disappear or only one wallet? Random or specific?
