### ISSUE TITLE
Unable to deploy any contract on Sync v1.1.0

### ISSUE THREAD

**Issue by shaurya-ObjC** [vechain/thor-sync.electron#359]
I am trying to deploy a small contract which was working perfectly on version 1.0.0, however when my Vechain sync updated to version 1.1.0 automatically, I am unable to deploy any contract on same. When I tap on deploy contract it simply shows me nothing. Even it doesn't opens a window for selecting any of the test account. So, I am unable to pay any vetho.

CODE what I am trying to deploy with compiler version: 0.4.24+commit.e67f0147.Emscripten.clang

pragma solidity ^0.4.24;

contract message {
    int myMessage;

    function setValue(int x) public {
        myMessage = x;
    }

    function getValue() public view returns (int) {
        return myMessage;
    }
}

Current Output:-  Nothing
And in console I see this only **"creation of message pending..."**

Expected Output:- Should return the address of contract where it's deployed.

Versions:- 
MacOS 10.13.6.
Sync - v1.1.0
Connex:  1.4.0
Electron:  3.0.16
Chrome:  66.0.3359.181
V8:  6.6.346.32

**Comment by AsbertMa** [comment]
@shaurya-ObjC Sync's feature or DApp?

**Comment by shaurya-ObjC** [comment]
It's on VIDE inside Sync.

**Comment by libotony** [comment]
Hi, @shaurya-ObjC I believe this is an issue of VIDE rather than Sync's. However, I have tried VIDE locally and it works fine when I try to deploy the default contract, it works fine. So I would suggest you open an issue in [VIDE repo](https://github.com/mobileteamdev/vide-web/issues/new)

**Comment by shaurya-ObjC** [comment]
Sure, thanks. Moved the issue to VIDE Repo.
