### ISSUE TITLE
Can't Make transfer from sync with NanoX

### ISSUE THREAD

**Issue by nelly874** [vechain/thor-sync.electron#366]
**Describe the bug**
I used NanoX for cold storage for vault.veforge.com. Now that I am having to use Sync I can't do anything with my acocunt like transfer/send the coins

**To Reproduce**
1. Go to 'My Tokens...'
2. Click on Transfer
3. Select Wallet then import
4.Nano X wallet show up with VET in it.
5. Click next and recieve error "Ledger device:INS_NOT_Supported(0x6d00)"

**Actual result:**

**Expected result:**

**Desktop OS :**
 Win10

**Sync Version:**
v1.2.0

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by AsbertMa** [comment]
@nelly874 
Check your device settings
Multi-clause
&
Contract-data

to yes

**Comment by AsbertMa** [comment]
@nelly874 

1. Check version(1.0.4) of VeChain app on your device
2. Settings of app 'contract data & multi clause' to yes

**Comment by JayWiseFree** [comment]
Describe the bug
Similar issue as OP.  Ledger Nano X, latest version of VET.  I can get past the first two steps: "Connect and unlock your Ledger device" and "Navigate to your Dashboard."  When I enter the VET app on my Nano X, it disconnects and re-starts the process.  Cannot get through.  Settings of app 'contract data & multi clause' ARE set to yes.

To Reproduce
Steps to reproduce the behavior:

Go to 'Wallets'
Click on Ledger icon in top right.
Import Wallet from Nano X prompt appears.


Expected result:

Desktop OS :
Win10

Sync Version:
v1.2.0

![vet error](https://user-images.githubusercontent.com/32954079/68905686-a73a4200-0707-11ea-85c6-7cfa0519da98.png)

**Comment by AsbertMa** [comment]
@JayWiseFree 
Try enter the VET app early. Before click the ledger icon. (Windows issue)

**Comment by nelly874** [comment]
I got my crypto thank you...



Sent via the Samsung Galaxy S9, an AT&T 5G Evolution capable smartphone


-------- Original message --------

**Comment by JayWiseFree** [comment]
@AsbertMa 

Thank you, worked like a charm.

**Comment by AsbertMa** [comment]
@JayWiseFree @nelly874 
Welcome
