### ISSUE TITLE
Vechain wallet frozen

### ISSUE THREAD

**Issue by Brian369** [vechain/thor-sync.electron#371]
Since the Veforge Vault website is no more in operation, I downloaded "Sync" and then I checked "My tokens" tab, which shows my Wallet with my VET and VTHO. Now, the observe button doesn't have any activity with my mouse. The transfer tab does not select my wallet but does select a new wallet that I have created. So I cannot move my tokens in to a wallet.  I also Vechain on Nano S, the process it get frozen after 2 check mark. See the picture file. What are  you suggesting to do ? Thanks

![Nano s](https://user-images.githubusercontent.com/27358544/68916798-90aadf80-0735-11ea-902c-692be7ebcc07.png)

**Comment by AsbertMa** [comment]
@Brian369 
1. Enter the VET app
2. Click the ledger icon
3. import your accounts into Sync.
4. Open My token app

**Comment by Brian369** [comment]
Thanks AsbertMa,
I did that, and the thing is the process freeze on number 3 (see the picture). The import process doesn't continue after the 2 green marks. The 2 blue arrows do not convert into green.

**Comment by AsbertMa** [comment]
Like this issue? @Brian369 
https://github.com/vechain/thor-sync.electron/issues/366

**Comment by Brian369** [comment]
Windows 8

**Comment by Brian369** [comment]
Windows 8

**Comment by AsbertMa** [comment]
@Brian369 
Try 
1. Enter the VET app early on ledger before the 'Import Ledger' pop up.
2. Keep the VET app and reopen the dialog.

We will check the windows 8

**Comment by Brian369** [comment]
It is working.
Thanks AsbertMa.
Have a great day!
