### ISSUE TITLE
OCE and PLA token dissapeared after "vault.veforge.com" out of service

### ISSUE THREAD

**Issue by gaaddaar** [vechain/thor-sync.electron#382]
**OCE and PLA token dissapeared after "vault.veforge.com" out of service**
VeForge adress had shows OCE and PLA tokens but Sync is not able

**VeForge had VET, OCE and PLA tokens but after Sync, i can not able to get OCE and PLA**

Import your wallet via Ledger,

**Actual result:**
There is no pic to prove that Veforge had OCE and PLA tokens

**Expected result:**

**Laptop :**
 Win10 

**Sync Version:1.2.1**

**Comment by libotony** [comment]
For managing tokens, please try [MyTokens App](https://tokens.vecha.in/#/) or [VeChain Tokens App](https://laalaguer.github.io/vechain-token-transfer/)

**Comment by gaaddaar** [comment]
VeCha,n Tokens App solved the issue
