### ISSUE TITLE
Sync does not connect with ledger

### ISSUE THREAD

**Issue by minobit** [vechain/thor-sync.electron#387]
Hello. I was trying today to connect my ledger nano to the sync so to transfer some coins but it does not connecting. Last time I connected it was about 1 month ago without any troubles. I checked ledger and is synchronized fine with ledger live and sync is up to date.
The coins in sync are visible and staking, no problem with that at all.
Anyone else with the same problem?

**Comment by libotony** [comment]
If you are trying with `Ledger Live` opening and connected to your device, please close `Ledger Live` and try again.

**Comment by minobit** [comment]
Thanks for your reply. No, it can not be that, I was not having the Live open. I just opened the live to check that the problem was not with the ledger itself.  Its not connecting either way.

**Comment by libotony** [comment]
Could you provide more info on the issue template?
---
**Describe the bug**
Provide a brief description of the issue

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. 
3. 
4.

**Actual result:**
Please add screenshots if needed


**Expected result:**


**Desktop OS :**
 Win10/MacOS 10.14.2/.....


**Sync Version:**


**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by minobit** [comment]
Well I connect my ledger nano, I enter the vechain account in the ledger and when I want to send the coins through the sync it just does not connect.
![Untitled](https://user-images.githubusercontent.com/60655063/73749927-f753fe00-4764-11ea-9f8a-8454d0696884.png)
![Untitled2](https://user-images.githubusercontent.com/60655063/73749932-fae78500-4764-11ea-8280-f13ab8514f2a.png)

**Comment by minobit** [comment]
Windows 7 - sync v1.2.1 / Connex v1.4.0

**Comment by XJWX89** [comment]
Hi @minobit please try below steps
1. Connect you ledger
2. Enter VeChain app 
3. Open sync 
4. Try to access your ledger device

**Comment by minobit** [comment]
I had tried this before opening this issue. I just tried it again as you proposed but it does not making any difference. It just does not connect.

**Comment by minobit** [comment]
I even tried different usb ports on my pc just in case... no difference with that too.

**Comment by XJWX89** [comment]
thanks for the quick reply , could you provide following infos? 
1. Ledger version / VeChain app version 
2. virtual machine? ( yes /no)
3. Windows build version.  ( please check this [Microsoft support](https://support.microsoft.com/en-us/help/13443/windows-which-version-am-i-running)

**Comment by minobit** [comment]
1. Ledger Live 1.8.0 - sync v1.2.1 / Connex v1.4.0

2. No


3. Windows 7 pro service pack 1

I had no problems at all last time since I used Sync 1 month ago. There were no changes in my pc since then.

**Comment by XJWX89** [comment]
hi @minobit could you check the firmware version on ledger ?

**Comment by minobit** [comment]
1.5.5

**Comment by minobit** [comment]
Any ideas? Ohters with the same issue?

**Comment by XJWX89** [comment]
Hi @minobit, we are still investigating the issue. Meanwhile, please check out this link   [Fix connection issues](https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues)

**Comment by minobit** [comment]
I tried many things including checking on another pc, but finally the problem was the usb cable.
Many thanks for your help guys!
