### ISSUE TITLE
No option to select VTHO

### ISSUE THREAD

**Issue by bixboxfx** [vechain/thor-sync.electron#388]
Hello,

I have been able to move some VET in and out of the wallet but there is no option to select VTHO for the transfer. I select my wallet, then select Transfer but the amount always defaults to VET with no obvious opyion I can see to select VTHO.

How can I transfer VTHO to another wallet?

Thanks.

VeChain Sync
v1.2.1
Connex:  1.4.0
Electron:  3.0.16
Chrome:  66.0.3359.181
V8:  6.6.346.32

**Comment by qianbin** [comment]
You can try the dapp [My Tokens](https://tokens.vecha.in/#/).

**Comment by bixboxfx** [comment]
Thanks for this, I didn't know that existed. Is there an easy way to send the whole balance as I don't know what amount of "gas" will be deducted from the transfer amount? I want to avoid leaving tiny balances in the wallet and transfer the whole lot to leave an empty wallet.
