### ISSUE TITLE
Out of Sync

### ISSUE THREAD

**Issue by dexsword** [vechain/thor-sync.electron#389]
Just downloaded Sync 1.2.1
Imported wallet from Ledger
MAIN is Out of Sync 0%
Going to vechain.org fails in my browser (firefox 72.0.2)

**Comment by dexsword** [comment]
so I am having this odd issue and I've come here to see if anyone has an idea.

I have a cold wallet with my ledger nano I made months ago. Today I tried to download the Sync app on linux, but I had the error MAIN Out of Sync 0%. I tried to access vechain.org in my browser (firefox) and I was unable to connect. I tried to ping vechain in the terminal and it failed all attempts.

I then switched to win 10 and I had the same problem?! I then logged into my router and switch, made sure all firmware was updated. I ran a pin on vechain.org from my router and it works!

I then just went to vechain.org on my android phone on the wifi on the same network as my PC and it works fine. I went to vechain.org on the PC with chrome, and I got a connection rejected error.

I can access the internet fine on the PC. I am writing this post on the PC in question. It is only vechain.org I am having this bizarre issue with. I am very confused that it is the same on windows and linux on the same PC. That points to some odd firewall issue? there are no rules that I see in the configuration.

Anyone have any ideas?

Thanks

**Comment by libotony** [comment]
@dexsword I just had a quick check, the nodes are working fine. Your issue seems to be a network issue. Could you visit https://sync-mainnet.vechain.org  in your browser?

**Comment by dexsword** [comment]
No i am getting ERR_CONNECTION_REFUSED

-Will L.

**Comment by libotony** [comment]
If you know about [curl](https://curl.haxx.se/), can you try `curl -vvv https://sync-mainnet.vechain.org` and get back to us?

**Comment by dexsword** [comment]
* Rebuilt URL to: https://sync-mainnet.vechain.org/
*   Trying 103.210.21.121...
* TCP_NODELAY set
* connect to 103.210.21.121 port 443 failed: Connection refused
* Failed to connect to sync-mainnet.vechain.org port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to sync-mainnet.vechain.org port 443: Connection refused

I am going to bring my ledger to work and use it there. I was able to remote into work and confirm I can get to vehcain.org from the browser, so the sync app should also work.

I cannot understand what it is on or about my local network that would cause this. I have the sg-1100 with pfSense for my router/firewall. nothing else is broken that I can tell.

**Comment by dexsword** [comment]
I confirmed I can access the wallet from my work PC.
There is something about my LAN that must be causing an issue.

**Comment by libotony** [comment]
> I confirmed I can access the wallet from my work PC.
> There is something about my LAN that must be causing an issue.

Agree. In the meantime please try https://vethor-node.digonchain.com/ ,if you can access this URL, you can add it to sync as a [custom node](https://docs.vechain.org/sync/user-guide/browse-dapp-and-web.html#add-custom-node)

**Comment by dexsword** [comment]
> Agree. In the meantime please try https://vethor-node.digonchain.com/ ,if you can access this URL, 

I cannot access that URL either. Attempting to add it as a node throws a network error.
I will have to thoroughly review my router settings. I have not made any custom modifications so I'm not even sure what to look at specifically.

**Comment by dexsword** [comment]
I found the problem. I have pfBlockerNG installed to block outbound LAN traffic to suspect locations based on GeoIP. Turning off the filter fixes my issue, however I will continue to leave it on. I am curious why vehcain is being blocked.

**Comment by dexsword** [comment]
Feb 9 22:11:45 | LAN | pfB_Top_v4(1770011056) | TCP-S |   | 10.1.3.5:61708dexpc |   | 47.52.32.121:443unknown | HK | Country
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by libotony** [comment]
You can check the IP `103.210.21.121` at [https://www.iplocation.net/](https://www.iplocation.net/), it's from the cloud provider `UCloud` and located at `HK`

**Comment by dexsword** [comment]
No worries, I am all set. I will mark this issue closed. It was resolved by re-configuring (or disable) pfBlockerNG on my pfSense router, in case anyone else encounters this problem. Thanks for the help.

**Comment by cryptogawds** [comment]
I am having the same issue with 0% sync. I don't believe I have a pfBlockerNG so I'm not sure what's wrong with it. I reset my router and no luck, any thoughts?

**Comment by libotony** [comment]
hi @cryptogawds, please try to visit https://sync-mainnet.vechain.org in your browser to check your connection with the remote node.

**Comment by cryptogawds** [comment]
It does not seem to work in browser either. It says, your connection is not private.

**Comment by libotony** [comment]
@cryptogawds might be the network issue, how about https://vethor-node.vechain.com ?

**Comment by cryptogawds** [comment]
I can now open both on my browser as I fixed some settings in the brave browser, but it still does not sync in the sync wallet.

**Comment by libotony** [comment]
@cryptogawds please try to open the urls in the sync wallet

**Comment by cryptogawds** [comment]
Dang, both failed to open in sync wallet search

**Comment by libotony** [comment]
@cryptogawds could post screenshots?

**Comment by cryptogawds** [comment]
![Screen Shot 2020-06-30 at 8 54 19 PM](https://user-images.githubusercontent.com/67445919/86201263-ec36ab80-bb13-11ea-937e-0de6c3c8fb03.png)

**Comment by libotony** [comment]
If you know curl, could you try ` curl -vv https://sync-testnet.vechain.org` in your terminal?

**Comment by cryptogawds** [comment]
I don’t know curl :/

________________________________

**Comment by libotony** [comment]
> I can now open both on my browser as I fixed some settings in the brave browser, but it still does not sync in the sync wallet.

Could you tell me what steps did you perform on solving it on brave browser?

**Comment by cryptogawds** [comment]
I just had to press advanced once the error popped up and it has the option to proceed to the “unsafe” page

________________________________

**Comment by libotony** [comment]
I forgot to ask, is there any proxy or VPN in your system running? And the problem is not with the public node, most possible something wrong in your local environment

**Comment by libotony** [comment]
Please reveal the certificate in your `Brave Browser` and take a screenshot of the certificate(as detailed as possible). Follow the instructions in the screenshots.

## Steps

<img width="1312" alt="Screen Shot 2020-07-03 at 10 57 16 AM" src="https://user-images.githubusercontent.com/8411962/86427371-9e40c400-bd1c-11ea-9c49-cd553f241a23.png">

## Example of Certificate

<img width="1312" alt="Screen Shot 2020-07-03 at 11 00 06 AM" src="https://user-images.githubusercontent.com/8411962/86427380-a26ce180-bd1c-11ea-88b8-419a9f9bf694.png">

**Comment by cryptogawds** [comment]
I actually do have a VPN, which may be causing issues. Sync still says 0% in wallet when turning VPN off. I’m going to try that brave method right now

________________________________

**Comment by cryptogawds** [comment]
![Screen Shot 2020-07-02 at 8 09 56 PM](https://user-images.githubusercontent.com/67445919/86427810-1321e880-bca0-11ea-8391-9aebd752e2bc.png)

**Comment by libotony** [comment]
@cryptogawds What is the version your macOS ?

**Comment by cryptogawds** [comment]
OS X El Capitan

**Comment by libotony** [comment]
I think I know why. Your system contains an expired ca root certificate `AddTrust External CA Root` which issues the certificate of our HTTPS certificates. The recommended way is upgrading your system to the latest one. Below is some links that might be useful:

+ https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020
+ https://it.stonybrook.edu/news/articles/update-your-operating-system-andor-web-browser-if-you-get-certificate-error-or
+ https://security.stackexchange.com/questions/232445/https-connection-to-specific-sites-fail-with-curl-on-macos

**Comment by cryptogawds** [comment]
Cool got you, thanks for your help I really appreciate it.

________________________________

**Comment by libotony** [comment]
Welcome, hope you get synced :-)

**Comment by cryptogawds** [comment]
It looks like I have to get a new computer to update that specific addtrust external root because I can’t update the software any further. I was planning on doing so anyways. Quick question, in order to connect my sync account on my new computer with my ledger, would I just connect my ledger and import to gain access to my wallet? Thank you for your help!!

________________________________

**Comment by libotony** [comment]
Yes
