### ISSUE TITLE
Scan the QR code with your Cold Wallet

### ISSUE THREAD

**Issue by saurabh** [vechain/thor-sync.electron#390]
**Describe the bug**
Unable to put my X-Node which is held on my ledger up for sale using VeChainThor/Sync

Provide a brief description of the issue
My X-Node is linked to the VeChainThor app via an observe wallet. I am now interested in selling my node so going through the steps of putting it up through public auction, you eventually hit the "Scan the QR code with your Cold Wallet" screen which shows a QR code. "Please scan the QR code with your Cold Wallet and proceed after the signing is completed." How exactly do you do this? There's no option to do this via Sync either. I've checked all the dapps listed on Sync as well.

**To Reproduce**
1. Have an X-Node on your ledger listed as an Observe Wallet on the VeChainThor app.
2. Try and list your X-Node collectible for sale via public auction

**Actual result:**
Please add screenshots if needed

**Expected result:**

**Desktop OS :**
 Win10 Pro 1809

**Sync Version:**
1.2.1

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by libotony** [comment]
VeChain Foundation has published a bounty of [X Node and Economic Node Management Application](https://bbs.vechainworld.io/topic/325/concluded-developer-bounty-x-node-and-economic-node-management-application), there will be an app in Sync for you to  manage your nodes

**Comment by saurabh** [comment]
I see that the bounty has been concluded and the App assigned to a team. Do we have any idea what the timeline on this is?

**Comment by libotony** [comment]
I think the team is closing to publish the app, they have a [preview](https://twitter.com/VeChainStats/status/1218157690452496387) for us

**Comment by saurabh** [comment]
Oh that's amazing, twitter thread says should be published early February so could be any day now. Thanks for the info.

**Comment by saurabh** [comment]
Manager from VeChainStats is now live. Just wanted to leave this out for those who stumble here and are unaware of the solution. Also available as a dapp on the Sync App.

https://twitter.com/VeChainStats/status/1229797800994578437
