### ISSUE TITLE
import wallet with ledger problems

### ISSUE THREAD

**Issue by goossens01** [vechain/thor-sync.electron#391]
**Describe the bug**
I downloaded sync because i wanted a wallet with safety of the ledger nano S.

Did everything except "contract data" and "multi clause". created a wallet and import from wallet. I saw my VET in the wallet. But, i cannot send any VET. Problem with checking account info. 

I reinstalled de app on the ledger device and "contract data" and "multi clause" on YES!

I deleted the wallet on sync with adres 0x6820836858661C1233a6114D9bcB11Ab645486Ce

I import the wallet with the ledger device. Now i have a diverend wallet adres and can not see my VET anymore.

Please help me because i don't know what to do write now. I am scared i have done something wrong.

Greetings,

Dennis

Provide a brief description of the issue

**To Reproduce**
2. 
3. 
4.

**Actual result:**
Please add screenshots if needed

**Expected result:**

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**
created january 2020

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by libotony** [comment]
I have checked your address in the [explorer](https://explore.digonchain.com/accounts/0x6820836858661c1233a6114d9bcb11ab645486ce/), there is no VET in the account, do you know the addresses in your ledger?

**Comment by goossens01** [comment]
thank you sir for checking. I have solved the problem. It was my other ledger device. Everything is ok now. Sorry for the confusion
