### ISSUE TITLE
Checksum doesn't match?

### ISSUE THREAD

**Issue by jameejay** [vechain/thor-sync.electron#397]
**Describe the bug**
I downloaded both the txt and exe from https://env.vechain.org/. I'm using Quick Hash to compare. Although, the file sizes do match. 

**Actual result:**
![image](https://user-images.githubusercontent.com/30181160/74462380-21d94180-4e5e-11ea-8753-2afab8a0ffca.png)

**Desktop OS :**
 Win10

**Sync Version:**
1.2.1

**Comment by AsbertMa** [comment]
@jameejay 
Convert the .exe file's hex string to base64, then compare the base64 string with the txt's content.
[https://base64.guru/converter/encode/hex](url)

**Comment by jameejay** [comment]
> @jameejay
> Convert the .exe file's hex string to base64, then compare the base64 string with the txt's content.
> [https://base64.guru/converter/encode/hex](url)

Checks out just fine. Thank You.
