### ISSUE TITLE
Can't even open Sync

### ISSUE THREAD

**Issue by tosypian** [vechain/thor-sync.electron#402]
**Describe the bug**
I just downloaded 1.2.2 for Mac and when I try and open it, I get this message:

The application “Sync” can’t be opened.

**Desktop OS :**
Mac 10.15.3 (19D76)

**Sync Version:**
1.2.2

**Additional context**
I tried looking in my Security System Preference to see if I could authorize it but didn't see that option.

**Comment by libotony** [comment]
@tosypian It might be your downloaded file is not complete, check the checksum of the file first. Try `shasum -a 512 Sync-mac-1.2.0.dmg | cut -f1 -d\ | xxd -r -p | base64`.

**Comment by ctspeck** [comment]
I am having the same issue

**Comment by XJWX89** [comment]
hi @ctspeck  ，Is there any message prompt?

**Comment by libotony** [comment]
@tosypian @ctspeck Please download the dmg file from https://env.vechain.org and try again.
