### ISSUE TITLE
export transaction history

### ISSUE THREAD

**Issue by finehobby** [vechain/thor-sync.electron#403]
is it possible to export the transactions of VET and VTHO in sync-wallet or other way?

**Comment by XJWX89** [comment]
Hi @finehobby, I'm not sure what you are asking . can you elaborate  it?

**Comment by finehobby** [comment]
Hi, i want to export all my transactions at Sync for example the incoming VET,VTHO, to a .csv-file with
date, time, to-/from-adresses, type in/out, amount, currency, fee
just like provided from exchanges.  I need it for tax declaration

**Comment by XJWX89** [comment]
Hi @finehobby, unfortunately, export cvs file is not supported.

**Comment by AsbertMa** [comment]
@finehobby Try [Explorer](https://explore.vechain.org)
