### ISSUE TITLE
Can't successfully run "npm run dev" on Windows

### ISSUE THREAD

**Issue by adaaaam7777** [vechain/thor-sync.electron#404]
**Describe the bug**
On windows currently on node version 10.18.1 (higher gave other errors). Managed to run npm install without problems. With npm run dev I get the following:

`  ERROR in C:/Users/me/dev/thor-sync.electron/src/renderer/components/AddressLabel.vue
  ERROR in C:/Users/me/dev/thor-sync.electron/src/renderer/components/AddressLabel.vue(47,28):
  TS2532: Object is possibly 'undefined'.

  ERROR in C:/Users/me/dev/thor-sync.electron/src/renderer/components/AddressLabel.vue
  ERROR in C:/Users/me/dev/thor-sync.electron/src/renderer/components/AddressLabel.vue(47,54):
  TS2532: Object is possibly 'undefined'.

  ERROR in C:/Users/me/dev/thor-sync.electron/src/renderer/components/Amount.vue
  ERROR in C:/Users/me/dev/thor-sync.electron/src/renderer/components/Amount.vue(36,28):
  TS2532: Object is possibly 'undefined'.

  ERROR in C:/Users/me/dev/thor-sync.electron/src/renderer/components/Amount.vue
  ERROR in C:/Users/me/dev/thor-sync.electron/src/renderer/components/Amount.vue(36,54):
  TS2532: Object is possibly 'undefined'.

  ERROR in C:/Users/me/dev/thor-sync.electron/src/renderer/components/CertActivityItem.vue
  ERROR in C:/Users/me/dev/thor-sync.electron/src/renderer/components/CertActivityItem.vue(44,17):
  TS2349: This expression is not callable.
    Type 'typeof import("C:/Users/me/dev/thor-sync.electron/node_modules/timeago.js/lib/index")' has no call signatures.`

Thanks

**Comment by AsbertMa** [comment]
@adaaaam7777 
1. Make sure that your code has no changes
2. Delete the node_modules folder
3. re-install and try again

**Comment by adaaaam7777** [comment]
I did that several times :(

**Comment by AsbertMa** [comment]
My dev env is 10.16.3, i had tried 10.18.1 on windows; that's ok.

But looks like TS issue.

```
TS2349: This expression is not callable.
Type 'typeof import("C:/Users/me/dev/thor-sync.electron/node_modules/timeago.js/lib/index")' has no call signatures.`
```
check the file 'C:/Users/me/dev/thor-sync.electron/node_modules/timeago.js/lib/index'
