### ISSUE TITLE
ledger sync no sending vtho

### ISSUE THREAD

**Issue by Dirkbelgie** [vechain/thor-sync.electron#409]
i have vtho standing on ledger and using sync  But i can not transfer my vtho to other exchange  When i tried ad token ,there is still a problem and i can not send my vtho  I got the message  data nok  I can send vet ,but not vtho  How comes we can not choose in sync vet or vtho  ???

**Comment by XJWX89** [comment]
hi @Dirkbelgie  you can try myTokens(https://tokens.vecha.in) to transfer the vtho

**Comment by Dirkbelgie** [comment]
Hey XJWX89  i already did that and still it is not working  ,i got message something wrong with data

**Comment by XJWX89** [comment]
@Dirkbelgie are you trying to transfer all the vtho? if so please deduct the transfer amount around 80 vtho .

**Comment by Dirkbelgie** [comment]
yes i tried all vtho   ok i m going to try with 80 vtho   thanks  When it works  i m happy and thank you very much when i wont work i come back  xxx

**Comment by Dirkbelgie** [comment]
no it wont work with 80 vtho(fee51vtho not good eh)   i always get the message   invalid data receved (0x6a80)

**Comment by XJWX89** [comment]
@Dirkbelgie  please follow the guide to solve the issue https://docs.vechain.org/sync/user-guide/import-ledger.html#troubleshooting

**Comment by Dirkbelgie** [comment]
ok thanks  i already did this before  I don t understand what is going wrong  I thank you for you re help ,but why would it not be possible simply to choose by sync send vet or vtho  Normaly i had stand all my vet on the ledger ,but i shall transfer it to another exchange so i can transfer my earnd vtho much easier than with the sync app   Thank you very much for trying to help me  xxx

**Comment by XJWX89** [comment]
hi @Dirkbelgie , could you check the version of the VeChain App & Ledger device firmware ?

**Comment by Dirkbelgie** [comment]
hey XJWX89 now its working There was something wrong with my windows. But also with youre help switching data and multidata to yes and my it man ,at last i could transfer my vtho to my ocean account. Thanks a lot for you re help and if you ever been in belgium and we meet ,i pay a few beers or wine to thank you
grts dirk

**Comment by Dirkbelgie** [comment]
by the way,,you can transfer a lot of vtho ,so you dont have to do it with 80 ,but you can tranfer as much as you want.  Thanks and have a good healty ,succesfull life xxx
