### ISSUE TITLE
Sync does not recognize Ledger

### ISSUE THREAD

**Issue by kreggj** [vechain/thor-sync.electron#410]
I was forced to reset my Ledger device. I have Sync wallets that contain VET and VTHO. After resetting my Ledger, the device does not seem to see any of my Sync wallets. When I "Navigate to the Vechain app" it's successful. However, "Checking account info" fails with a red ! so I cannot send at all.  I have not tried to receive at this point.

**Comment by XJWX89** [comment]
hi @kreggj  , as you mentioned that you reset the ledger , did you initialize as a new device or restore from mnemonic phrases?

**Comment by kreggj** [comment]
> hi @kreggj , as you mentioned that you reset the ledger , did you initialize as a new device or restore from mnemonic phrases?

Hi - I had to initialize as a new device.  My Ledger was compromised.

**Comment by XJWX89** [comment]
here's the solution :
1. import the "new ledger" into sync and copy a address 
2. import the "compromised wallet " into sync  (use mnemonic phrases to import)
ps . if the asset is in the first account of ledger . otherwise you need to reset the ledger device and restore the mnemonic phrases 
3. transfer your asset to new address

please make sure you have the  mnemonic phrases of "new ledger" .

**Comment by kreggj** [comment]
> here's the solution :
> 
> 1. import the "new ledger" into sync and copy an address
> 2. import the "compromised wallet " into sync  (use mnemonic phrases to import)
>    ps . only if the asset is in the first account of ledger . otherwise you need to reset the ledger device and restore the mnemonic phrases
> 3. transfer your asset to new address
> 
> please make sure you have the mnemonic phrases of "new ledger" .

I just want to make sure I'm understand you so I do this correctly and not make things worse.

To import "the new Ledger" in Sync there are 3 options -  the mnemonic phrase is all I have and I'm EXTREMELY reluctant to enter my Ledger phrase anywhere but the Ledger itself.
#2 when you say "compromised wallet", do you mean the Ledger? Meaning the original mnemonic phrase?
Note: after I discovered my Ledger had been compromised, I sent all of my VET to an exchange. After I initialized my Ledger as a new device I sent my VET back to my Sync address successfully.
When I downloaded Sync on my Laptop I was not presented with a backup phrase option. Sync created 5 accounts and I was off and running.

**Comment by XJWX89** [comment]
1.you need to import the new ledger into sync . Click the ledger  on upper right and follow the steps to import 
2.  the origin ledger 

I’m curious about you mentioned “ I sent my VET back to my Sync address successfully.”  If the funds are in your sync address , you can just do the transfer and no need to deal with the original ledger

**Comment by kreggj** [comment]
Correct - I sent it from an exchange to my existing Sync address.  Now I cannot move the assets from the original wallet address.
[Sync troubleshooting.docx](https://github.com/vechain/thor-sync.electron/files/4553564/Sync.troubleshooting.docx)

**Comment by XJWX89** [comment]
i see , just following the steps i provided. 
you should able to access your original ledger wallet and make the transfer to your new ledger wallet.

make sure you have original ledger & new initialize ledger mnemonic phrases.

**Comment by kreggj** [comment]
What do I do if my original Ledger seed is corrupt? When my device was compromised I reset it and set it back up as a new device. On the Ledger, I'm being told (I selected 12 words) that they are incorrect.

**Comment by kreggj** [comment]
I was finally able to access the old seed and move my assets.  Thank you for your assistance.  It's much appreciated.
