### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by harryfriend** [vechain/thor-sync.electron#412]
I open a ETH wallet on sync on the local side. I send ETH to the address that i created from my ledger nano x. It was confirm in my ledger live, but i'm not seeing the tokens in my wallet in Sync

**Comment by BeeArze** [comment]
@harryfriend Did you check it on [etherscan](https://etherscan.io/)?

**Comment by harryfriend** [comment]
Yes, it shows the transaction completed. But i am seeing in the wallet that i created in Sync

**Comment by BeeArze** [comment]
@harryfriend There are two different blockchains, etherscan for ethereum blockchain; sync for VeChain blockchain. If you want the ETH, you need a wallet for Ethereum.

**Comment by BeeArze** [comment]
@harryfriend https://ethereum.org/wallets/
