### ISSUE TITLE
Wallet not showing Reset Password, Backup and Delete Options

### ISSUE THREAD

**Issue by brodaw** [vechain/thor-sync.electron#414]
**Describe the bug**
I have created Sync wallets from Nano Ledger X. When I click on the individual wallet detail I am not given the 'Reset Password', 'Backup' and 'Delete' options. Only 'Transfer' and 'Verify' appear.

**To Reproduce**
1. Go to wallets 
2. Select individual Nano X wallet
3. Reset Password, Backup and Delete not displayed

**Actual result:**
Please add screenshots if needed
Reset Password, Backup and Delete options do not appear as per user guide. Only Transfer and Verify

**Expected result:**
Wallet detail to show Reset Password, Backup, Transfer and Delete options 

**Desktop OS :**
 MacOS 10.14.6

**Sync Version:**

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by XJWX89** [comment]
hi @brodaw , reset password/ backup/ delete is manage by the ledger device itself. if you are willing to "delete" the wallet from sync, you can follow the instruction [here](https://docs.vechain.org/sync/user-guide/import-ledger.html#remove-ledger-device)

Ps. 
1. remove action will not affect any change for  your ledger. It ONLY removes the display on sync.

**Comment by XJWX89** [comment]
This issue is closed due to not being active. Please feel free to open it again if you have further questions
