### ISSUE TITLE
Sync 1.2.5 browser is not starting

### ISSUE THREAD

**Issue by Stefan1986200** [vechain/thor-sync.electron#415]
**Describe the bug**
Provide a brief description of the issue
**Dear all, 
i am using the Vechain Sync browser and it was working properly so far.
Now after a few weeks not using it I wanted to start the browser, but it is not opening anymore.
It is just freezing in the starting window "VechainSync" and that for hours.
I uninstalled and reinstalled everything even with different Sync Versions. But so far still the same proplem.**

**To Reproduce**
1. Start Sync.exe
2. Browser is freezing and not continuing to the working surface
3. 
4.

**Actual result:**
Please add screenshots if needed
![sync](https://user-images.githubusercontent.com/67631429/86108432-6ee34a80-bac3-11ea-9507-e1becf7db1cd.JPG)

**Expected result:**
Starting and using the browser including ledger

**Desktop OS :**
 Win10/MacOS 10.14.2/.....
Windows 10

**Sync Version:**
1.2.5

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by XJWX89** [comment]
hi @Stefan1986200 , could you try to connect another wifi or try to connect to your mobile hotspot?

**Comment by Stefan1986200** [comment]
Hi there,

In the meantime I have just reset my notebook, since my cache and folders got corrupted. Now it’s working again. Thank you
