### ISSUE TITLE
"ValidationError: ForkTsCheckerWebpackPlugin Invalid Options" on "npm run build / dev" | Version: 1.2.5

### ISSUE THREAD

**Issue by BaoPham92** [vechain/thor-sync.electron#417]
**Describe the bug**
**_ValidationError: ForkTsCheckerWebpackPlugin Invalid Options_** seems to be the problem preventing the build / dev scripts within the files of the node_modules folder **schema-utils**. I tried navigating to the file validateOptions.JS in node_modules, but couldn't find the specific file within the package folder. The file was apart of the error message in the second image below the document.

<img width="555" alt="Screen Shot 2020-07-02 at 1 49 08 PM" src="https://user-images.githubusercontent.com/26471655/86393311-ddaed800-bc6a-11ea-9a03-666edce66d03.png">

**To Reproduce**
1. Git clone repo
2. cd directory
3. npm install
4. npm run build / dev

**Actual result:**
<img width="839" alt="Screen Shot 2020-07-02 at 1 10 21 PM" src="https://user-images.githubusercontent.com/26471655/86390096-6e82b500-bc65-11ea-90a7-031cf008ff0f.png">

**Expected result:**
Production / Development build for testing.

**Desktop OS :**
OS: Catalina 10.15.5

**Sync Version:**
Version: 1.2.5

**Additional context**
It might be worth adding I spent a day resolving an issue with a **_Scrypt_** package error preventing a proper npm installation, no idea if that would have any effect.

Prior to the reproduced error, I had done the following:
- Brew doctor, cleanup, and upgrade.
- Downgraded from version 12 Node to version 10 (I believed this resolved the npm installation **_Scrypt_** error)
- I saw how the package  **_schema-utils_** had recently been updated, so I downgraded to previous version of package, same results.
- Attempted searches on Stackoverflow

**Comment by libotony** [comment]
> Downgraded from version 12 Node to version 10 (I believed this resolved the npm installation Scrypt error)

You are right.

> ValidationError: ForkTsCheckerWebpackPlugin Invalid Options 

I did a quick test in my local environment, I didn't find `schema-utils` in `fork-ts-checker-webpack-plugin/node_modules` directory, how about remove `node_modules`, reset `package.json` and `package-lock.json` and perform a clean install by `npm ci`

**Comment by BaoPham92** [comment]
> how about remove `node_modules`, reset `package.json` and `package-lock.json` and perform a clean install by `npm ci`

Follow those series of steps solved the issue for me, thanks!

I had followed similar steps when attempting to solve the ```Script``` error beforehand that I didn't realize to try something similar on this issue afterwards.
