### ISSUE TITLE
Mnemonic and password issue

### ISSUE THREAD

**Issue by TheEagle2021** [vechain/thor-sync.electron#418]
Hi, my password and mnemonic words are not being accepted for some reason. I wrote them down at the creation of my wallet. I have attempted to follow all instructions without success, can i please have some guidence or assistance. Has this happenend previously to other wallet users and if so how did they manage this.

**Comment by TheEagle2021** [comment]
Thw wallet appears to be locked??

**Comment by BeeArze** [comment]
Importing wallet by mnemonic words?? @TheEagle2021

**Comment by XJWX89** [comment]
This issue is closed due to not being active. Please feel free to open it again if you have further questions
