### ISSUE TITLE
Not getting test tokens from vechain faucet

### ISSUE THREAD

**Issue by hedgehog34** [vechain/thor-sync.electron#419]
**Description of issue**
I can't top up my test wallet with test tokens when using faucet.vecha.in.

**To Reproduce**
1. Go to https://faucet.vecha.in/
2. Click "Claim Tokens" button
3. Choosing test wallet from list and trying to sign it in by providing my password
4. Geting electron notification "cert singed"
5. Getting message "Something wrong here, try again"

No errors in the console

**Actual result:**
"Something was wrong" message

**Expected result:**
Tokens added to test wallet

**Desktop OS :**
 Mac

**Sync Version:**
1.2.5

**Comment by libotony** [comment]
Hi @hedgehog34 there is some issue of faucet backend, we are working on that, if you need test tokens, paste address here, l’ll send manually.

**Comment by libotony** [comment]
@hedgehog34 Faucet is back online, please try again. Let us know if you have further questions.

**Comment by hedgehog34** [comment]
Hey @libotony thanks a lot for looking into it, but I'm still having same "Something wrong" message from faucet. If you could send test tokens to this wallet address that would be great:
0x677a9ead234F213aF078986388EF3e4c1CEC0734
I hope you'd be able to solve faucet backend.

**Comment by libotony** [comment]
Sent
https://explore-testnet.vechain.org/transactions/0xef23f191abf5b7286f4dd889e38c32379fa17d02722343e3f06ae67b9e587dce#info
and
https://explore-testnet.vechain.org/transactions/0x353518c46630747167fc63e38cc9d901587fe4d1cf93ac41972a165dc0e0109c#info

**Comment by hedgehog34** [comment]
Thanks @libotony I can see them being in my wallet now. Thanks a ton. This will help me to play with Vechain Dapps. I'm closing it here, since it's faucet related issue. 
Where can I check the state of the faucet, in case I'll have similar problem?

**Comment by libotony** [comment]
I think our dev community could do, don't hesitate to raise any topic to discus
