### ISSUE TITLE
Withdrawing VTHO from Sync wallet

### ISSUE THREAD

**Issue by munashe2003** [vechain/thor-sync.electron#424]
**Describe the bug**
I cannot transfer VTHO from my wallet to OceanEX using Desktop Sync App and Ledger nano S

**To Reproduce**
1. I went to the wallet with VTHO and selected  Transfer
2. It give the option to enter the destination address and the amount
3. The pull down menu for the coin/token only gives me the option to send VET. 
4.

**Actual result:**
See Attached Screenshot

**Expected result:**
i want to be able to send VTHO from my wallet to OceanEX

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**    1.2.6  connexx version 1.4.0
![VTHO](https://user-images.githubusercontent.com/41142510/87239304-4e5ead00-c440-11ea-917b-479340302c8f.png)

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by XJWX89** [comment]
Hi @munashe2003  you can transfer VTHO here :
MyTokens App:
Https://tokens.vecha.in/#/wallets
VeChain Tokens App:
https://laalaguer.github.io/vechain-token-transfer/

**Comment by loupiote** [comment]
I have the same issue.

I tried Https://tokens.vecha.in/#/wallets.  Does not work:

When I go there, it starts Sync, and when Sync tries to import my wallet from the Ledger, it displays the following error message:
Ledger device: INS_NOT_SUPPORTED (0x6d00)
My Ledger Nano X has the latest firmware 1.2.4.1 and I installed the latest VEChain app on the device.

https://laalaguer.github.io/vechain-token-transfer/ pops an error telling: "This web page needs VEChain Sync.  Download Sync", but I already have Sync installed on my win10 system. Whethet it is open or not makes no difference.

So at this point I am still unable to transfer out my VTHO... any solution?

**Comment by loupiote** [comment]
NOTE: This issue is specific to the Ledger-Nano-X.  I don't have the issue when using a Ledger-Nano-S.
EDIT: Problem resolved by installing VEChain app version 1.0.7 on the Ledger-Nano-X

**Comment by mvkrein** [comment]
I am having the same issue.  I do have VeChain app version 1.0.7 on my Ledger-Nano-X, but the problem persists.

**Comment by loupiote** [comment]
@mvkrein "but the problem persists." - what problem precisely?

**Comment by mvkrein** [comment]
The problem described above.  It is the same problem noted by @munashe2003.

**Comment by loupiote** [comment]
There are several problems described above.  The fact that you cannot see VTHO in Sync is not a problem, it is normal.

to see tokens, you need to use the app pr wallet that can see the tokens, e.g. https://tokens.vecha.in/#/wallets

so if you could describe your problem precisely, it would help. what app are you using, and what exactly is your problem?

**Comment by mvkrein** [comment]
Here is the problem:  I can see VTHO in Sync, but I can't select it to perform any action.

**Comment by loupiote** [comment]
This is not a problem, this is normal.  Sync by itself cannot send VTHO.

You need to use another wallet, e.g.  https://tokens.vecha.in/#/wallets

**Comment by loupiote** [comment]
or start Sync, and select "My Tokens" on the first screen.  that works too.

**Comment by mvkrein** [comment]
OK, I attempted to use "My Tokens" and send my VTHO to another address.  I received the error: Ledger Device: Invalid data received (0x6a80).  I did follow the steps in the Ledger Device troubleshooting guide.

**Comment by mvkrein** [comment]
I was able to transfer VET using "My Tokens" but not VTHO.

**Comment by mvkrein** [comment]
Ah, I missed this.  Now it works.
Ledger device: INCORRECT_DATA (0x6a80).

In VeChain App Setting ,set Contract data to Yes
In VeChain App Setting ,set Multi-clause to Yes

**Comment by mvkrein** [comment]
Thanks for your help!

**Comment by mvkrein** [comment]
...except now Insight MainNet transaction shows as Reverted.  So while it appeared to work, the transfer didn't occur.

**Comment by loupiote** [comment]
maybe try again?

i was able to tranfer my VTHO this way.

**Comment by mvkrein** [comment]
It just won’t work.  It appears to be sent correctly, but the transaction always reverts.

 

0x9221627ef59a0b1a333c5e98dd12809565d5fe877a0578c30dcc316f01c44ebc

**Comment by loupiote** [comment]
you know that you need to pay fees (in VTHO), in order to send a transaction, right?

if your fees are too low or 0, transaction wont go through.

**Comment by mvkrein** [comment]
I cranked it up to the max and it still doesn’t work.

**Comment by loupiote** [comment]
i have no idea why, hope someone else can help you there...

**Comment by mvkrein** [comment]
I give up.  The wallet just doesn’t work.

**Comment by BeeArze** [comment]
<img width="707" alt="WechatIMG93" src="https://user-images.githubusercontent.com/59358819/88614637-b957e700-d0c2-11ea-8d80-73ef4f49ff63.png">
@mvkrein  check the picture
2(transfer VTHO) + 3(fee) <=(less of equal) 1(the VTHO you have)

**Comment by mvkrein** [comment]
OK, I have resolved this now.  Thank you for your help.  My problem was that I assumed the “energy” would be deducted from the amount of VTHO I was trying to transfer.  So I was attempting to send the maximum amount of VTHO in my wallet without realizing I needed to leave some VTHO behind to provide the required energy.   Yes, you described the issue exactly!

 

An interesting note is that all my failed transactions still managed to reduce my balance of VTHO, even though the transaction failed.  I guess this was my punishment for being a moron.

**Comment by BeeArze** [comment]
`An interesting note is that all my failed transactions still managed to reduce my balance of VTHO, even though the transaction failed.  I guess this was my punishment for being a moron.`
Because your Txs change the Blockchain's status, just paid for that. 
Glad to help you.
