### ISSUE TITLE
Sync freezes when clicking on ledger icon 

### ISSUE THREAD

**Issue by jdow333** [vechain/thor-sync.electron#426]
If someone could please advise me on this issue 

I open the sync app
Go to my wallets 
Click on the ledger icon top right and then the app freezes 
Same happens when I navigate to manager 
Click login/start dApp
My wallet shows up i select my wallet click next and then the app freezes again.
Any process that involves the ledger freezes the Vechain Sync

I've tried reinstalling Sync 
Tried connecting the ledger before opening Sync 
I've tryed reinstalling VET app on the ledger V1.0.7

Sync V1.2.6 Connex V 1.4.0
Ledger live V2.8.0
Running on Windows 10
Nano s V1.6.0 used as a backup 
Nano x V1.2.4-2 used as main 
Contract data yes
Multi-clause yes 

Any insights would be greatly appreciated

**Comment by libotony** [comment]
@jdow333 Could post the screenshot of Sync in the frozen state ？

**Comment by jdow333** [comment]
![20200715_064946](https://user-images.githubusercontent.com/68303423/87508547-8c89e580-c667-11ea-9e04-aaaee67d6f98.jpg)
![20200715_064605](https://user-images.githubusercontent.com/68303423/87508553-8dbb1280-c667-11ea-9bf9-f5aba25e1aa5.jpg)
![20200715_064427](https://user-images.githubusercontent.com/68303423/87508559-8eec3f80-c667-11ea-8b14-2d7ddfed3e7e.jpg)

**Comment by jdow333** [comment]
Thats the frozen screen. From there I have to close the app down and open it up again if I want to do anything. The only way to close the app is to right click on the icon then close window.

**Comment by jdow333** [comment]
Normally a screen should pop up asking me to connect my ledger

**Comment by AsbertMa** [comment]
@jdow333 Hi, I want more infos. Could you please toggle the developer tools and then click the ledger icon. Then post the screenshots of the developer tool.
right-top the more icon could open the developer tool

**Comment by jdow333** [comment]
I'm at work now. Ill do that when I get home and send the info. Thank you for your help

**Comment by jdow333** [comment]
So I feel stupid 
It was my antiviras software that was the problem.
Thank you for taking the time to help
