### ISSUE TITLE
Can't Transfer VTHO between Ledger wallet and Sync Wallet

### ISSUE THREAD

**Issue by tomdewaart** [vechain/thor-sync.electron#429]
<img width="704" alt="Screenshot 2020-07-17 at 1 20 32 PM" src="https://user-images.githubusercontent.com/68414162/87751496-b2aeb180-c830-11ea-8e51-3e87d77fc9dc.png">

I get an error message the whole time I am trying to transfer my VTHO tokens between Ledger and Sync wallet. After I need to confirm with my ledger it gives me this error message uploaded as screenshot.

**Comment by XJWX89** [comment]
hi @tomdewaart , here is the solution  [Ledger Troubleshooting](https://docs.vechain.org/sync/user-guide/import-ledger.html#troubleshooting)

**Comment by tomdewaart** [comment]
@XJWX89 XJWX89
After I set Multi-clause to Yes, and set Contract data to Yes it worked for me. 
(this was stated in the troubleshooting) 
Thanks for your help
