### ISSUE TITLE
VTHO Issue

### ISSUE THREAD

**Issue by dorrinsports** [vechain/thor-sync.electron#431]
I transfered VET to my Ledger account fro the local wallet, but now I can not transfer the VTHO.  There is no option to do so.

**Comment by AsbertMa** [comment]
You can try the dapp [My Tokens](https://tokens.vecha.in/#/).

**Comment by AsbertMa** [comment]
@dorrinsports 
You can try the dapp [My Tokens](https://tokens.vecha.in/#/).

**Comment by dorrinsports** [comment]
ok thank you.
Sean

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 6, 2020 at 8:51 PM, Asbert Ma<notifications@github.com> wrote:   


@dorrinsports
You can try the dapp My Tokens.
