### ISSUE TITLE
Help recovering assets sent to wrong wallet type

### ISSUE THREAD

**Issue by irishruler** [vechain/thor-sync.electron#432]
I am new to wallets and crypto in general. I moved some of my VET off of crypto.com to external wallet at the advice another investor. I then also created another wallet and moved over some CELR assets. What I didnt know at the time was the wallet I created for the CELR was still a VET wallet. I sent over the assets to it and now they are gone. I was told by crypto.com to reach out to the external wallet for help in recovery. Not sure who to contact.

**Comment by BeeArze** [comment]
@irishruler CELR looks like an ERC-20 token on [Ethereum](https://etherscan.io/). So search the external wallet on Ethereum check the CELR assets.
https://etherscan.io/address/YourExternalWalletAddress

**Comment by irishruler** [comment]
> @irishruler CELR looks like an ERC-20 token on [Ethereum](https://etherscan.io/). So search the external wallet on Ethereum check the CELR assets.
> https://etherscan.io/address/YourExternalWalletAddress

That was very helpful and thank you! What can I do after I find it to recover it

**Comment by BeeArze** [comment]
> > @irishruler CELR looks like an ERC-20 token on [Ethereum](https://etherscan.io/). So search the external wallet on Ethereum check the CELR assets.
> > https://etherscan.io/address/YourExternalWalletAddress
> 
> That was very helpful and thank you! What can I do after I find it to recover it

Import your external wallet by 'private key' or 'keystore' into [eth wallet](https://ethereum.org/en/wallets/)
Please always double check the receiver.

**Comment by irishruler** [comment]
I will have to do some research on this still a noon when it comes to this. I will definitely not make the mistake of sending to wrong wallet type again.  I see my original transaction just need to figure out next steps with your guidance you provided!

**Comment by irishruler** [comment]
> 
> 
> > > @irishruler CELR looks like an ERC-20 token on [Ethereum](https://etherscan.io/). So search the external wallet on Ethereum check the CELR assets.
> > > https://etherscan.io/address/YourExternalWalletAddress
> > 
> > 
> > That was very helpful and thank you! What can I do after I find it to recover it
> 
> Import your external wallet by 'private key' or 'keystore' into [eth wallet](https://ethereum.org/en/wallets/)
> Please always double check the receiver.

Thank you so much for pointing me in the right direction. I was able to recover what had been lost for over a month. It was $30 back when I lost it and near $180 now. Your a life saver!
