### ISSUE TITLE
VeChain Sync, 5 empty addresses

### ISSUE THREAD

**Issue by cell182** [vechain/thor-sync.electron#433]
My problem is that VeChain Sync only displays five empty addresses and not the one where I have my assets. Thus I can't see nor access my VET & VTHO on neither VeChain Sync nor on My Tokens (https://tokens.vecha.in/#/wallets).

**To Reproduce**
1. Start VeChain Sync
2. Click 'Wallets'
3. Click 'MyLedger' -> five empty addresses appear
4. Goto https://tokens.vecha.in/#/wallets
5. Click 'import'
6. Open Sync? Click 'Open Sync'
7. "Wallet16" displayed, which has another name than the first empty wallet in Sync, but the same address.
8. Click 'Add'
9. Click 'IMPORT'
10. Select first empty wallet in Sync
11. Click 'next'
12. (connects to Ledger)
13. Confirm import of certificate, the hash of which is correct in both popup and Ledger.
14. Popup 'cert signed'
15. Still only have the same empty "Wallet16" to choose from.
16. If going to 'Transfer' in My Tokens and doing the import there, the result is the same.

**Actual result:**
![empty_vechain_addresses](https://user-images.githubusercontent.com/69979500/90804231-32d9a280-e31a-11ea-9903-d46564e28229.jpg)
![MyTokens empty wallet](https://user-images.githubusercontent.com/69979500/90804424-7df3b580-e31a-11ea-8b96-86de25a804d4.jpg)

**Expected result:**
I would expect to see all my VeChain wallets in VeChain Sync, or at least and in particular the one where I have all my VET & VTHO.

Versions:
PC, Windows 10 Pro, 10.0.18363, 64 bit
Ledger Nano S, Firmware 1.6.1
Ledger Nano S - VeChain App 1.0.7
( Ledger Live 2.10.0 )
VeChain Sync v1.2.6 / Connex v1.4.0

**Additional context**
For a long time I was doing fine with Ledger and VeChain Sync only, as long as I only needed to send/receive VET.
The problems started after I upgraded all to latest OR because I started using My Tokens (for VTHO).
My belief is that by now I've created too many new wallets on My Tokens out of which only the last five empty ones are displayed in Sync.

Note: My Tokens says "Required Connex environment is not supported. Please download VeChain sync for a frictionless experience" although Sync is installed already.

I can confirm the existence of my VET & VTHO by using explore.vechain.org on the right address.

**Comment by XJWX89** [comment]
Hi @cell182 , due to it may contain sensitive information, please contact support@vechain.com for further assis
