### ISSUE TITLE
Cannot get my VeChain out of Sync to my Ledger Nano X- hope I did not set up an ETH address...

### ISSUE THREAD

**Issue by Kmab3** [vechain/thor-sync.electron#434]
Hi Friends, I have an important questions about a withdrawal I made from Binance to Sync wallet. I was aiming to get it into my Ledger Nano X hard wallet, and it seems to be 'stuck' in Sync...although I have set up the VeChain application on my Nano...How do I make the transfer from Sync to Ledger. I see the Transfer and Verify at the top of the Sync wallet and it just keeps saying Application is ready....

**Comment by XJWX89** [comment]
Hi @Kmab3 ,Ledger device only responds when you request Ledger device to sign the transaction or certificate. Therefore, you need to "send" the request from sync to your ledger device. once ledger receives the signing request, you can check the transaction/certificate details on your ledger. please check the [doc](https://docs.vechain.org/sync/user-guide/interact-with-dapps.html#interact-with-dapps). 

1. select the wallet you willing to transfer out the asset
2. click transfer and filling the fields. 
3. at this moment, you will see the signing request pop-up. Click next to continue. 
4. follow the steps to complete the signing.
