### ISSUE TITLE
[Windows] Poor UX finding Sync launch shortcut

### ISSUE THREAD

**Issue by mikegogulski** [vechain/thor-sync.electron#435]
**Describe the bug**
The Sync launcher can't be found in either the Start menu or via search for "VeChain".

**To Reproduce**
1. Go to Start and look for VeChain or go to search and enter "vechain"

**Actual result:**
Nothing found

**Expected result:**
The application shortcut is either available in the Start menu under a "VeChain" folder, or findable in Search as "VeChain Sync", or preferably both.

**Desktop OS :**
 Win10

**Sync Version:**
1.2.6

**Comment by AsbertMa** [comment]
@mikegogulski Did you try the keyword ‘sync’？

**Comment by mikegogulski** [comment]
Yes, and of course that works. But it's a very generic term.
