### ISSUE TITLE
Sync verification Ledger wallet

### ISSUE THREAD

**Issue by Irishrobert** [vechain/thor-sync.electron#441]
**Describe the bug*Navigating to the Vechain app" it's successful. However, "Checking account info" fails with a red ! so I cannot send at all. I also have  tried to receive and  on the transfer sheet it shows that I received the vechain,but it did not add to the summary.I made this sync account without password and no phrase I have this Sync account about a year and it always worked good with sending and receiving.And now my ledger does not verify the account.I badly need a solution for this problem.Hope you can help me.I am attaching the screenshot of the problem. Regards for now.
Robert
[Vechain.docx](https://github.com/vechain/thor-sync.electron/files/5418188/Vechain.docx) 

Provide a brief description of the issue

**To Reproduce**
2. 
3. 
4.

**Actual result:**
Please add screenshots if needed

**Expected result:**

**Desktop OS :**
 Win10/MacOS 10.14.2/.....I am using windows 10 

**Sync Version:** 1.2.6

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by XJWX89** [comment]
Hi @Irishrobert , in this case , it means that your device and the wallet you've imported into sync mismatch . please double make sure you have the correct mnemonic phrase .

**Comment by Irishrobert** [comment]
Dear,ShaohuaiW
When I downloaded the sync to make an account I did not have to make any password or phrase.
The account was sync with my ledger nano s I used for more than 6 months  very often with sending and receiving
Vechain it always worked very properly  and I never had any problem up to a few days ago.
I really do not understand this the more you say that I have check my mnemonic phrase I never had a mnemonic phrase
or password.I still hope that this problem can be solved somehow because I have a lot of vechain on the wallet and
I really do not want to lose them in this way.I hope that you can help me.Regards
Robert

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by XJWX89** [comment]
Hi @Irishrobert , the mnemonic phrases I mentioned are that when you first start using the ledger device, the ledger device will ask you to write down the 24 mnemonic phrases.  

In sync ledger device management, it only imports the ledger accounts into sync. All the security is managing by the ledger. Therefore, when you imported your ledger,  Sync will not ask you to backup or set a password for the imported wallet.

The easiest way to verify your ledger is the "same" wallet you imported. You can click the ledger icon on the upper right wallet page (ledger icon). if it becomes a separate wallet, then you might need to check your mnemonic phrase in your ledger device is the same.

As you mentioned, it showed the issue a few days ago. I just wondering if you upgrade the firmware/version? Sometimes, the upgrade ledger device will ask you to choose if you want to initialize your device or restore it from the mnemonic phrase.

**Comment by Irishrobert** [comment]
Hi XJWX89,Thanks for giving me the advice I now understand what the problem is.
I do upgrade the firmware whenever their is a new version.I am going to try what you told me and I will
certainly tell you the result thank you so much.Regards
