### ISSUE TITLE
I can't transfer VTHO from Ledger

### ISSUE THREAD

**Issue by ricardomoura1979** [vechain/thor-sync.electron#442]
**Describe the bug**
Provide a brief description of the issue
When I open my Ledger showing my Vechain Wallet with VET and VTHO using the app SYNC, I am able just to transfer just VET. I cant change to VTHO.

**To Reproduce**
2. 
3. 
4.

**Actual result:**
Please add screenshots if needed

**Expected result:**

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by Fpaspapa** [comment]
Same question for me.... How to transfert VTHO.. I can only transget VET.. Where can I read How to do ? thanks
![Transfer VTHO ](https://user-images.githubusercontent.com/79396591/108624444-4f7ba200-7445-11eb-8add-f0bb1a65718e.jpg)

**Comment by yahehe** [comment]
This is affecting me as well, no option to switch to VTHO

**Comment by AsbertMa** [comment]
@yahehe @Fpaspapa Try [VeChain Manager](https://manager.vechainstats.com/) or [My Tokens](https://tokens.vecha.in/)

**Comment by yahehe** [comment]
Yes that worked for me, forgot to report back. I went there in the Sync browser and it all clicked. Thanks!
