### ISSUE TITLE
Connect Sync Wallet to VeChainThor Wallet

### ISSUE THREAD

**Issue by cmaciasochoa** [vechain/thor-sync.electron#447]
It is not possible to connect to VeChainThor Wallet, only able to obser a sync wallet from mobile wallet will be awesome!

**Comment by libotony** [comment]
[Manager](https://manager.vechainstats.com/vnt-manager/#transfer1) from [VeChainStats](https://vechainstats.com/) will help

**Comment by XJWX89** [comment]
This issue is closed due to not being active. Please feel free to open it again if you have further questions
