### ISSUE TITLE
SYNC transfer to Exchange 

### ISSUE THREAD

**Issue by crypticlo** [vechain/thor-sync.electron#453]
**Describe the bug**
Provide a brief description of the issue
I attempted to transfer VeChain to my ledger Nano X, and was instructed to use the SYNC app. I'm now having difficulty transferring my VET to an exchange off SYNC. I'm continually receiving an "insufficient energy"  notification and failed transaction. can some one assist me I removing my VEChain one sync and on to an exchange. or explaining how I can attain more VeThor

**To Reproduce**
2. 
3. 
4.

**Actual result:**
Please add screenshots if needed

**Expected result:**

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by BeeArze** [comment]
@crypticlo https://github.com/vechain/thor-sync.electron/issues/424#issuecomment-664750302

**Comment by crypticlo** [comment]
ahh. I think I understand. I must wait for my VeChain to generate enough VTHOR to perform a transfer.
