### ISSUE TITLE
I cant access my VET coins by using SYNC app. Since I dont have my keystore information

### ISSUE THREAD

**Issue by kerimbasa** [vechain/thor-sync.electron#455]
I cant access my VET coins by using SYNC app. Since I dont have my keystore information.

**Comment by BeeArze** [comment]
@kerimbasa  Do you have the private key of mnemonic words?

**Comment by kerimbasa** [comment]
Hi yes I do have the mnemonic words for my Ledger Nano X, but when I bought the VeChain I did not have the Nano Ledger that time so I never stored them there before. They were stored in Veforge Vault and since Oct 2019 they are closed and I can’t find my coins :-(

**Comment by BeeArze** [comment]
Is the mnemonic words for your ledger same as the mnemonic words in Veforge Vault.

**Comment by BeeArze** [comment]
@kerimbasa How did you create the wallet? Comet or Sync?

**Comment by kerimbasa** [comment]
I did not have a ledger that time when I bought the VeChain coins. I just transferred them from binance to Veforge

Regards,
Kerim Basaran

**Comment by BeeArze** [comment]
@kerimbasa 
Open [My Token](https://tokens.vecha.in/#/) in Sync, and import the wallet address

**Comment by kerimbasa** [comment]
ok great I managed to import the wallet and can see the coins now, but when I try to transfer to my ledger account using sync I am not able to choose the imported wallet with Vechain coins under From option.

Can you help? is there an  explanation video about this or something?

**Comment by BeeArze** [comment]
@kerimbasa https://docs.vechain.org/sync/user-guide/

**Comment by kerimbasa** [comment]
Thank you, I really appreciate your prompt assistance :-) I have this link already and read it 100 times :-(

Since I don't know my keystore, private key and mnemonic words for my VeChains I can’t do any transfer! it is just sitting under my coins now and can not transfer them to ledger Vechain wallets I created.

**Comment by BeeArze** [comment]
And the wallet not in your Sync? 
https://web.archive.org/web/20190518210624/https://vault.veforge.com/

**Comment by kerimbasa** [comment]
I can only see the coins under “My coins” icon in Sync not in Wallet.

This link is getting stuck not opening, see below.

**Comment by BeeArze** [comment]
Don't care about the link. Give me a screenshot like below.
<img width="1000" alt="WechatIMG118" src="https://user-images.githubusercontent.com/59358819/106876607-d5dc7800-6712-11eb-8c71-eb6ac38bd62d.png">

**Comment by kerimbasa** [comment]
here is a screenshot from ledger

**Comment by kerimbasa** [comment]
??? what do you suggest from this point?

**Comment by kerimbasa** [comment]
Hi,

Are you still receiving my emails? Can you pls help me to secure my coins in my ledger? We are alsnog there 

Regards,
Kerim Basaran

**Comment by BeeArze** [comment]
@kerimbasa Looks like you have got your VET
[How to transfer vechain coins from Sync "my tokens" to ledger Nano X](https://github.com/vechain/thor-sync.electron/issues/459#issue-805296040)

**Comment by kerimbasa** [comment]
Hi Why the casu is closed? I am still not able to access my coins.

**Comment by AsbertMa** [comment]
@kerimbasa Not your keys; not your coins. Get the keystore first.

**Comment by kerimbasa** [comment]
how can I get the keystore? I don't have any info about it. all I have is the VET address where my coins were send from my Binance account to veforge vault. I don't remember getting any keystore or mnemonic words while I set up veforge vault. I checked all my emails, files, etc... nothing
