### ISSUE TITLE
invalid data recieved 0x6a80

### ISSUE THREAD

**Issue by Tammada1771** [vechain/thor-sync.electron#456]
**Describe the bug**
invalid data recieved 0x6a80, anytime i try to send vethor 

**To Reproduce**
2. 
3. 
4.

**Actual result:**
Please add screenshots if needed

**Expected result:**

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by BeeArze** [comment]
@Tammada1771  Do you have any error messages of screenshots?

**Comment by BeeArze** [comment]
@Tammada1771 https://docs.vechain.org/sync/user-guide/import-ledger.html#troubleshooting
