### ISSUE TITLE
Cannot enter any dapp via Ledger device

### ISSUE THREAD

**Issue by belgacoin** [vechain/thor-sync.electron#457]
**Describe the bug**
After concluding steps 1 and 2 with my Ledger Nano S to Sync wallet, I can't go to step 3 (Navigate to Vechain app) since the wallet software jumps back to step 1 again.

OS: Windows 10 with latest updates for Windows and updated Sync wallet.

![IMG_7050](https://user-images.githubusercontent.com/4160284/106752194-7440de80-662a-11eb-9e31-89c5e95b336b.jpg)

**Comment by BeeArze** [comment]
@belgacoin  Did you navigate to VeChain app in ledger

**Comment by belgacoin** [comment]
yes, it's when I navigate to the Vechain app in the Ledger, after clicking it, Sync Step 1 is again activated, like it's in a loop.

**Comment by BeeArze** [comment]
It's not 100% repeatable on my Windows, I got the situation.

Trick Way:

1. Navigate to the VeChain app
2. Click the next button
3. Check the Tx/Cert info on device

**Comment by belgacoin** [comment]
It suddenly worked again without doing any updates. Don't know what the reason was...
