### ISSUE TITLE
When I click on my VIM, that new page with enlarged VIM does not show anymore

### ISSUE THREAD

**Issue by billethekid** [vechain/thor-sync.electron#458]
When I click on my VIM, that new page with enlarged VIM does not show anymore. 

This page will not load anymore

<img width="1483" alt="Schermafbeelding 2021-02-04 om 11 34 25" src="https://user-images.githubusercontent.com/35973445/106880688-f689db00-66dc-11eb-9f1e-a13c81c3f9dc.png">

**Comment by AsbertMa** [comment]
@billethekid  Please contract VIM for help.
https://www.vimworld.com/contact
