### ISSUE TITLE
How to transfer vechain coins from Sync "my tokens" to ledger Nano X

### ISSUE THREAD

**Issue by kerimbasa** [vechain/thor-sync.electron#459]
I managed to find my Vechains with sync under 'my tokens' however from there I am not able to transfer and/or see them in my ledger nano X VeChain wallet. I created the Vechain wallet (1-5) which I can see but from my tokens I am not able to transfer them.

Can somebody please help?

**Comment by BeeArze** [comment]
@kerimbasa 
1. The Wallet A has the VET
2. Ledger nano x wallet(1-5) doesn't have the VET
3. You want to transfer VET FROM Wallet A TO One of your Ledger nano x wallet(1-5)
![screenshot](https://user-images.githubusercontent.com/59358819/108453645-da259b00-72a5-11eb-8420-2943135f5d13.png)

**Comment by kerimbasa** [comment]
@beearze.

The Wallet A with the coins I see is aN OBSERVE wallet, therefore I am not able to select is as a transfer from wallet. When I click Transfer /from the only wallet I can choose is Wallet 8( which is one of my Ledger nano x wallet(1-5)


See below screen shots

**Comment by BeeArze** [comment]
@kerimbasa If it is an observable wallet then you cannot transfer it out. It is READ-ONLY.

Find your real wallet with private key, keystore or mnemonic words.

**Comment by kerimbasa** [comment]
@beearze that’s the problem I don't have any private key, keystore or mnemonic words.

I bought them on Binance 3 years ago and transfer them to Veforge Vault. at that time I did not get and/or set-up  any of the  (private key, keystore or mnemonic words)

only information I have is the wallet address from Binance transfer history!

**Comment by BeeArze** [comment]
@kerimbasa So how you created the wallet?

**Comment by kerimbasa** [comment]
@beearze you mean when I transferred the coins from binance to veforge vault

Regards,
Kerim Basaran

**Comment by BeeArze** [comment]
@kerimbasa 
The 'to' address, How you get the address when you transferred the coins from binance to veforge vault

**Comment by kerimbasa** [comment]
@beearze

I know it sounds weird but I only find that out that in the transaction history details of binance

Regards,
Kerim Basaran
