### ISSUE TITLE
VET and VTHO not visible on Ledger.

### ISSUE THREAD

**Issue by khanccg** [vechain/thor-sync.electron#460]
**Describe the bug**
Provide a brief description of the issue

**To Reproduce**
1. Open Sync application
2. Select Ledger + Open VeChain App
3. Accounts open
4. Does not display my VET
5. Can see on VeChain Explorer that it is there

**Actual result:**
Please add screenshots if needed
<img width="1003" alt="Screen Shot 2021-02-20 at 5 49 02 PM" src="https://user-images.githubusercontent.com/79387280/108613135-fd367480-73a3-11eb-8c57-87d0265ba3eb.png">

<img width="1280" alt="Screen Shot 2021-02-20 at 5 46 40 PM" src="https://user-images.githubusercontent.com/79387280/108613110-a7fa6300-73a3-11eb-8d93-34614fa34956.png">

**Expected result:**
Simply to display me VET.
This worked a few weeks ago when I checked last, but not it does not work.

**Desktop OS :**
MacOS: 10.13.2 

**Sync Version:**
v1.3.0

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue

**Comment by jlsdcgithub** [comment]
I am having the exact same issue you've described.

**Comment by shaakmeat** [comment]
The same is happening to me.

**Comment by mulitray-lab** [comment]
Me too, cant see my token balance, but main explorer stil shows my tokens are still in there.

**Comment by Sneakypotates** [comment]
Seems to be a certificate error, as I get a connection refused -102 possibly an expired certificate? PC date and time are correct.

**Comment by nooh43** [comment]
refer to :
https://github.com/vechain/thor-sync.electron/issues/462

posted how I managed to solve the issue

**Comment by libotony** [comment]
Sorry for the inconvenience, I believe the issue has been solved. Closing this now, feel free to reopen this if you want further discussion.
