### ISSUE TITLE
VET & Vethor Balance not showing up.

### ISSUE THREAD

**Issue by Dirtyazzbyrd** [vechain/thor-sync.electron#462]
I am unable to withdraw.
The Vechain mainnet is also out of Sync

![Capture2](https://user-images.githubusercontent.com/79389367/108614706-e5261b80-73ca-11eb-973b-be8d2a44b27a.PNG)
![Capture](https://user-images.githubusercontent.com/79389367/108614550-801df600-73c9-11eb-8bc8-d22f123ca419.PNG)

**Comment by Dirtyazzbyrd** [comment]
The Vechain mainnet is also out of Sync

**Comment by nooh43** [comment]
I managed to solve the issue by using a different access point :

https://mainnet.veblocks.net

**Comment by Humanoid1990** [comment]
please fix wtf is going on!!!!!

**Comment by nooh43** [comment]
> please fix wtf is going on!!!!!

The fix is up there, just update the access point

**Comment by Humanoid1990** [comment]
what do you mean by fixing the access point? How do I go about making that change.

**Comment by nooh43** [comment]
> what do you mean by fixing the access point? How do I go about making that change.

1. go to settings

2. scroll down to "default node"

3. Click "Add node"

4. type whatever you want in the name like for example "mainnet fix"

5. insert this into the URL section :
**https://mainnet.veblocks.net**

6. click on main next the the refresh page symbol

7. select the fixed node

this is how it was fixed for me, just selecting another access point.

**Comment by khanccg** [comment]
Awesome it worked! 
Thanks.

**Comment by Dirtyazzbyrd** [comment]
Mannnn you are awesome.  I appreciate it. Worked like a charm.



Sent from my Sprint Samsung Galaxy Note10+.



-------- Original message --------

**Comment by radishzz** [comment]
Oh Thank you I been up all night and now I found this you are a star Thank you so much My Friend

**Comment by libotony** [comment]
Sorry for the inconvenience, I believe the issue has been solved. Closing this now, feel free to reopen this.
