### ISSUE TITLE
Sync not working properly

### ISSUE THREAD

**Issue by p8ng** [vechain/thor-sync.electron#463]
Currently using Sync with Ledger. Problem suddenly occured today. It was working fine before.

After going to manager and onto the certiftication identification page, wallet shows address but it doesn't show VET / VTHO amounts. Both appear as a bunch of dashes, "-----".  I'm able to log in but VET/VTHO continues to show "dashes" on the main page. I am, however, able to see the values in EUR and USD. Also, I'm not able to send funds because when I try maximum amount, it's 0. I've checked the blockchain and my funds are still there. 

In addition, my partner has VET on her ledger and she is experiencing the same thing. To summerize, I've tried two different ledgers on 3 different computers. I've also reached out the reddit community, some people are experiencing the same problem

Please fix or advise a solution

Thanks,
Thomas 
VET believer/investor)

**Comment by nooh43** [comment]
Update the access point to : 
https://mainnet.veblocks.net
and it will work perfectly fine

**Comment by p8ng** [comment]
sorry kinda noob here, how do i update the access point?

**Comment by roygilbo** [comment]
I believe I have the same problem.  However, I do not see USD amounts in my Sync Wallet, but I do see the tokens on vechainstats.com

**Comment by p8ng** [comment]
@roygilbo: Likewise, i can see usd and eur amounts, cant see tokens, can't send funds.

**Comment by radishzz** [comment]
Hi same here Hi I am having a problem with my VetChain Wallet I have been using it with the nano Ledger
![1111QCapture](https://user-images.githubusercontent.com/79395495/108618703-22fd6100-7418-11eb-8afb-ebd1ad7fee71.PNG)
 I login to my VetChain sync account the balance does not show I have to click on my Dashborad Then the page reloads and I can see my cash balance But my VetChain Token amount is not there It shows  like this   ---------VET But the cash balance is there also my recent transfers are not there and there is tinny circle spinning as if its trying to load my recent transfers I just sent some more VetChain to my wallet to see if it would load my recent transfers But it did not work But it added the VetChain to my balance I also tried to see if I could send any of my VetChain out of the wallet  and it is coming up as zero balance Could you help me please I would be so greatful Like I say the balance is there Once I click on my Dashborad  Thank you very  From Conrad

**Comment by libotony** [comment]
Sorry for the inconvenience, I believe the issue has been solved. Closing this now, feel free to reopen this.
