### ISSUE TITLE
moving vet and vtho  from vechainthor mobile wallet (observe)

### ISSUE THREAD

**Issue by AJ77B** [vechain/thor-sync.electron#466]
history:  2019 my vet was moved from VeForge  vault(does not exist)  and exchange  to vechainthor mobile wallet
2020  setup vet  with with ledger.  Moved some vet  from exchange  to ledger into one of the five wallets for nanox.

In vechain manager, (My tokens)   I have created my Observe wallet(show my current tokens) and  my ledger wallet (current tokens).
Using manager:  I see my nanox accounts and local accounts.   My tokens  ( observe wallet) does not show up ?

Using sync, what is the process of transferring  from vechainthor mobile wallet (observe) to to one of my ledger nanox accounts or local accounts?
 
I have not to date seen any step by step procedure that explains this process.
Your assistance would be appreciated

**Comment by laalaguer** [comment]
You cannot transfer from Observe wallet. It is called "observe" because it is read-only.

**Comment by AJ77B** [comment]
Thank you for your reply.
What I am having difficult with  in vechain thor mobile wallet(android)  transferring tokens on my  phone..  cold wallet is what I don't understand.  I have to scan it, but where do I find this wallet.  Confused on the process. Have not used the mobile wallet for years.  Sorry for all the questions, I'm lost in this process.
Appreciate your help.
