### ISSUE TITLE
Sync wallet SHA512 checksum not matching.

### ISSUE THREAD

**Issue by SpencerAndrews** [vechain/thor-sync.electron#468]
Hello all,

I downloaded the Sync wallet and before installing I checked the SHA512 checksum with Hashcalc which returned:
4564b0537700a2b9e104d184cf803dee5a3ea5b0c8bc1516f5fca7877ade84b3b486302be4cdda866f5c7e5918aa1f5104b82e48ed40033b3b74ffe93272a12f

The checksum document for windows located at https://env.vechain.org/#sync called "Sync-win-130.exe-sha512-base64.text" shows this:
RWSwU3cAornhBNGEz4A97lo+pbDIvBUW9fynh3rehLO0hjAr5M3ahm9cflkYqh9RBLguSO1AAzs7dP/pMnKhLw==

Am I mistaken?

Thanks for your help,

Andrew

**Comment by libotony** [comment]
The content in file "Sync-win-130.exe-sha512-base64.text" is `base64` encoded, try [this](https://base64.guru/converter/encode/hex) online tool to convert your hash result to base64 encoded.

**Comment by SpencerAndrews** [comment]
I guess I should have realized that. It worked of course. Thank you!
