### ISSUE TITLE
Transferring VTHO out of Vechain Sync

### ISSUE THREAD

**Issue by eisakn** [vechain/thor-sync.electron#470]
Hey – I'm trying to transfer the full amount of my VTHO out of Vechain Sync (https://tokens.vecha.in/#/wallet). When I tell it to transfer, it provides me confirmation of the request, but doesn't actually transfer anything and charges me the transfer fee. 

Please help.

**Comment by eisakn** [comment]
Ok. I tried again, and reduced the amount to transfer by about 52 VTHO. This time I think it worked. 

Is there any chance of somehow getting the 102 VTHO back that was charged to me for the two failed withdrawals?

**Comment by libotony** [comment]
@eisakn I think you already found the root cause, it described here https://docs.vechain.org/sync/faq.html#how-to-transfer-all-vtho.

> Is there any chance of somehow getting the 102 VTHO back that was charged to me for the two failed withdrawals?

Unfortunately, no. That's the tx fee paid for nodes that packed your transaction.

**Comment by XJWX89** [comment]
This issue is closed due to not being active. Please feel free to open it again if you have further questions
