### ISSUE TITLE
can not transfer VET from Sync wallet, ledger X to Binance account

### ISSUE THREAD

**Issue by kratosphs** [vechain/thor-sync.electron#473]
Everytime I tried to transfer VET from my Sync wallet using ledger nano X to my Binance acount  I get the red dropped signal, and on the transaction screen insufficient energy message and everything transaction dropped.

**Comment by AsbertMa** [comment]
@kratosphs https://github.com/vechain/thor-sync.electron/issues/424#issuecomment-664750302

**Comment by XJWX89** [comment]
This issue is closed due to not being active. Please feel free to open it again if you have further questions
