### ISSUE TITLE
Unsure how to transfer to recipient address - transferring VET to Nano X

### ISSUE THREAD

**Issue by pepito2103** [vechain/thor-sync.electron#474]
Hello, 

As I am trying to transfer VET to Nano X through the Sync app, I am stuck when I am trying to transfer to the recipient address. How do I find this recipient address??

Thanks a lot in advance for your help!

![VET](https://user-images.githubusercontent.com/82888675/115437842-fb0a5e00-a20c-11eb-9467-16dd85524756.png)

**Comment by XJWX89** [comment]
hi @pepito2103 ,
recipient address: address of the person/application/exchange ⋯etc you would like to send the asset to. it start with 0x + 40 characters
In sync, you can go to the wallet page, 
1. Select the address you are willing to receive the asset 
2. Copy the address, start with 0x + 40 characters
3. Paste in the recipient address field

**Comment by XJWX89** [comment]
This issue is closed due to not being active. Please feel free to open it again if you have further questions
