### ISSUE TITLE
Do not see coins in account.

### ISSUE THREAD

**Issue by partycrasherband** [vechain/thor-sync.electron#475]
Hello,
I went to check my balance using this sync App and my VET coins do not appear to be in the balance.  

**To Reproduce**
1. I opened my Sync app
2. See my VET wallets
3. No balance of either VET or VTHOR

What do I do?

**Expected result:**
I hope to recover my coins.

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**
SYNC V 1.3.0

I deposited these coins about 2 month ago.

PLEASE HELP !!!

**Comment by XJWX89** [comment]
hi @partycrasherband, please make sure the address is the same. 
base on the information you provided, I'm guessing the address you own(address in sync ) and the deposited address is not the same. 
if you can check the deposit details(via exchange/application which you make the deposit), check/compare the deposit address. if you have the mnemonic words with you, you can try to import the address via wallet import.

**Comment by delboy900** [comment]
hi, i can see my VET balance in my Sync Ledger wallet (not local) but I can't see VET account in Ledger Live app. Is that normal?

**Comment by XJWX89** [comment]
@delboy900 yes,  VeChain accounts can not be added to Ledger Live.

This issue is closed due to not being active. Please feel free to open it again if you have further questions
