### ISSUE TITLE
**VeChain Thor Wallet Import Issue**

### ISSUE THREAD

**Issue by MrFisk3313** [vechain/thor-sync.electron#476]
**Wallet Import or Software**
I have followed the below steps. I get the “Import Successful” for both options when typing in the "Mnemonic Phrase” 12 word phrase  and or copy and pasting the "Keystore File” both of which I have and  I need to access my wallet. Why is it not importing my wallet/Vechain Assets?In addition I did my own troubleshooting, when I alter either the 12 word phrase or keystore file in any manner it does not say "import succefull" 

**To Reproduce**

To import a Backup phrase (12 words) into VeChainThor Wallet
Open VeChainThor Wallet
Go to “Me”, press “Manage Wallets”
Press “import a wallet”
Choose “Mnemonic Phrase” option, type in the words
Enter the wallet name and password
Press “import”

To import a keystore file into VeChainThor Wallet
Open VeChainThor Wallet
Go to “Me”, press “Manage Wallets”
Press “import a wallet”
Choose “keystore” option, use your keystrore file or use the keystore QR code to input your keystore
Enter the wallet name and password
press “import”

**Actual result:**
A new wallett address imports for each method used. for example a new wallett address imports whenusing the 12 word phrase. A new wallet address is generated when I use the copy N paste with the Keystore File. Both new walletts have no assets in them. 

**Expected result:**
I expect to see the 242,070.14 VeChain in the new wallett address when importing assets from a previous wallet to a new one. Its currently worth 1 BTC or 60KUSD

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**

**Additional context**
I have been a long time believer in Vechain and the idea that the project is a real world solution for real world problems. I generally look forward to the digitizng of the world. However in general people cant just LOOSE access to THEIR assets. This project and the entire digital movement is suppose to empower people, not consume their assets from them. With relationships with BMW, Walmart, Salesforce do they loose access to ANYTHING within the Vechain Software/Blockchain or is it only thr little guys who cant be assisted? THis is truly a sad day for one crypto and blockchain enthusiats.

**Comment by XJWX89** [comment]
hi @MrFisk3313 , for VeChainThor Wallet , please contact support@vechain.com for further assistance.
