### ISSUE TITLE
ALL VET TOKENS GONE?

### ISSUE THREAD

**Issue by jef23god** [vechain/thor-sync.electron#477]
Imported my wallet using Mnemonic 12 words  - balance says 0 for both VET and VTHOR?  I have kept a log (hash) for all VET sent to this wallet - had a lot of VET - now gone? What happened? submitted -17:31 25/04/2021

**Comment by jef23god** [comment]
Dear VECHAIN
NO RESPONSE FROM VECHAIN - CONSIDERING LEGAL ACTION -
I had over 10,000 VET coins -sync wallet
I have kept a log of all my VET purchases -
my sync wallet says I have 0 balance?
I have evidence of transactions via SIMPLESWAP (multiple HASH) =
my public key -
0x4651d6b183Da519ddEc1d61Edc94186089831F06 -
I have records / evidence of purchases via SIMPLESWAP -
Please advise -
Jeff 
London UK

Tues 27/04/2021

**Comment by XJWX89** [comment]
hi @jef23god, Base on the information you provided, I'm guessing your mnemonic is incorrect or you transferred to the wrong address. if you need further support please elaborate on your issue ,  

eg, 
1. Where did you get the transferred address and how you created ?
2. Using ledger device?

**Comment by XJWX89** [comment]
This issue is closed due to not being active. Please feel free to open it again if you have further questions

**Comment by jef23god** [comment]
The issue was successfully resolved -  - thank you 
    On Monday, 31 May 2021, 03:20:04 BST, shaohuaiW ***@***.***> wrote:  
 
 


This issue is closed due to not being active. Please feel free to open it again if you have further questions
