### ISSUE TITLE
cannot transfer VTHO out of sync wallet; only VET

### ISSUE THREAD

**Issue by pdreyfuss** [vechain/thor-sync.electron#478]
I want to withdraw VTHO out of my sync wallet but I see only an option to withdraw VET

**To Reproduce**
1. Start vechain sync wallet.
2. I see my wallet there and click on it. I have only one.
3. I see that I have a  VTHO balance, and click on transfer at the top of the screen.
4. It asks for recipient address and amount in VET.
5. I put my exodus VTHO address as recipient - the system seems ok with that.
6. I could put in an amount for VET even though I don't have any, and I did try that. All it did was warn me, and when I went ahead anyway it reverted the transaction and subtracted some of my VTHO.
7. There is an up/down arrow near where it wants me to enter the VET amount and it increments or decrements the amount field by 1 - seems pretty useless since you would probably just enter the number you want.
8. Bottom line, I can't get ahold of the VTHO.

**Actual result:**
No option exists to select VTHO as the crypto to transfer, only VET

**Expected result:**
It should offer to transfer the same coins that are listed in my wallet, i.e. VET and VTHO

**Desktop OS :**
 Win10

**Sync Version:**
v1.3.0
2021 vechain.org
Connex:  1.4.2
Electron:  3.0.16
Chrome:  66.0.3359.181
V8:  6.6.346.32

**Comment by libotony** [comment]
Try https://tokens.vecha.in

**Comment by pdreyfuss** [comment]
That looks as if it will work, but now I'm rethinking if I want to move the VTHO. Anyway it's an odd fix but seems good. I will bookmark it and maybe use it later. Thanks._____________________________
Peter
**********************
"My name also is Ransom,” said the Voice.--from Perelandra by C.S. Lewis
********************** 

    On Friday, April 30, 2021, 03:39:53 AM EDT, libotony ***@***.***> wrote:  
 
 


Try https://tokens.vecha.in

**Comment by XJWX89** [comment]
This issue is closed due to not being active. Please feel free to open it again if you have further questions
