### ISSUE TITLE
TRANSFERING VET FROM KUCOIN ACCOUNT TO LEDGER WALLET, now they are GONE!!!

### ISSUE THREAD

**Issue by SPART20** [vechain/thor-sync.electron#479]
GOD help me please! I transferred 66K of VET from my Kucoin main account to my ledger nano wallet. After transfer I realized i didn't add the app, I then added it after the fact, never saw my 66k VET on the ledger side!!!! anything that can be done? please somebody help me.  Kucoin thinks says transaction was successfull i can view all the actions on the blockchain. what do I do???

**Comment by XJWX89** [comment]
hi @SPART20,  I'm guessing you transferred your VET to ethereum address. if so please follow the step [here](https://docs.vechain.org/sync/user-guide/import-ledger.html#mis-transfer-the-funds-to-ethereum-address).

**Comment by SPART20** [comment]
thanks for replying. yes I send my tokens to a ledger wallet thinking it would be ok. I look at the steps you send me, I installed sync, created a wallet, not sure what to do next. can you help me further please.

________________________________

**Comment by XJWX89** [comment]
1. [Export your account private key - *provided by ledger support*](https://support.ledger.com/hc/en-us/articles/115005297709-Export-your-accounts)
2. Import your exported account into Sync
3. [Import your Ledger device](https://docs.vechain.org/sync/user-guide/import-ledger.html#import-ledger-device)
4. Make a transfer from exported account to your ledger account

**NOTE**:
Please make sure VeChain APP is installed on your ledger device . you can install it via Ledger live

**Comment by XJWX89** [comment]
This issue is closed due to not being active. Please feel free to open it again if you have further questions
