### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by SG1DP3** [vechain/thor-sync.electron#482]
Can't find stored password and mnemonic words. I can add vet to ledger but I can not remove any.

**Comment by XJWX89** [comment]
hi @SG1DP3 , please elaborate your issue

**Comment by XJWX89** [comment]
@SG1DP3 if you can find the mnemonic words , you can use it to restore the wallet. i'm confusing about the password you mentioned . what password is it? is it the password you set when wallet created/imported? or is it the password of keystore file?

**Comment by XJWX89** [comment]
This issue is closed due to not being active. Please feel free to open it again if you have further questions

**Comment by SG1DP3** [comment]
LOL! I didn't find my password, but I did find the mnemonic words. Just 10 minutes ago. The password is what it asks for to transfer tokens from wallet to wallet.

**Comment by XJWX89** [comment]
hi @SG1DP3  , you can follow the steps to [reimport the wallet](https://docs.vechain.org/sync/user-guide/#import-wallet), if the mnemonic words is correct, you are able to reset the password .

**Comment by SG1DP3** [comment]
100% successful!! I was able to create a new password.

**Comment by XJWX89** [comment]
happy to hear that !  The mnemonic words stores all the information that is needed at any point in time to recover your wallet.please make sure you store your mnemonic words in secure place.
