### ISSUE TITLE
VET not received, but transaction is verified on block explorer

### ISSUE THREAD

**Issue by Oneltz** [vechain/thor-sync.electron#488]
Hello, I am wondering if this is the right place to seek help with the Sync wallet.  I sent some VET from Guarda wallet to my Sync wallet, but it never arrived. It shows completed and successful on the block explorer, however. Transaction ID: 0x8970cc4cc520279db1dbf3fe5bb4c36ae97e41efe25ab3bc6cecc0e8a5aa732a

Please advise, thank you,
Oneltz

**Comment by XJWX89** [comment]
hi @Oneltz, I checked the explorer and it shows that you make a transfer after vet received. [here](https://explore.vechain.org/accounts/0x8c6b07c36d1adfca5276b9e139045e6e88c7324c/transfer) is the transfer logs that indicated the details of vet transfer. 

if you need further assistance, please contact support@vechain.com

**Comment by Oneltz** [comment]
I see. Thank you for the clarification and the help.
