### ISSUE TITLE
Sync App wont open

### ISSUE THREAD

**Issue by BigD77** [vechain/thor-sync.electron#489]
I click on it and it just takes me to the help page

**Comment by XJWX89** [comment]
hi @BigD77 , please provide a brief description of the issue

To Reproduce Steps to reproduce the behavior:

1. eg. click on sync icon to open application
2. ....
3. .....

Actual result: Please add screenshots if needed

Expected result:

Desktop OS :

**Comment by BigD77** [comment]
Hi this is the screen it takes me too when I try to open it.
Thank you,

Darren

**Comment by XJWX89** [comment]
hi @BigD77 , I didn't see the screenshot you provided. could you try again to upload the screenshot?

**Comment by BigD77** [comment]
Ok that’s weird lets try again..

**Comment by XJWX89** [comment]
still  cant see the screenshot....maybe there's an issue of uploading image via email .......maybe you can try it on desktop?

**Comment by BigD77** [comment]
That was my desktop lol. I’ll try with my iPad now.



Thank you,

Darren

**Comment by XJWX89** [comment]
loll.....or try reply on browser not email ?

**Comment by BigD77** [comment]
Can you not see it now cause I see it on the reply on my end?

Darren

**Comment by XJWX89** [comment]
nah....still cant see it .... could you send an email to support@vechain.com and make sure the email subject is `github issue #489` ?

**Comment by BigD77** [comment]
Ok done.

**Comment by XJWX89** [comment]
hi @BigD77 ,  i saw the screenshot you provided . it is a *homepage* of the sync  application . you can either click an application from bottom area to explore the dApps or you can enter a dApp url. if you want to create a wallet [check here](https://docs.vechain.org/sync/user-guide/#create-wallet)

**Comment by BigD77** [comment]
Hi well my confusion is that I downloaded the app a while back and I can’t find my VET tokens. I sent them to MEW from Binance but they don’t see them. So I imported my wallet to SYNC and now that’s the page I get when I click on the app. Crazy.
Thanks for any help you can give me to find my tokens.

Darren

**Comment by XJWX89** [comment]
hi @BigD77 , it seems that you transferred the vet to Ethereum wallet (MEW),  I just asked support team to assist you to recover your token. 
you should receive the email shortly.

**Comment by BigD77** [comment]
Ok I’m waiting for it thank you.

Darren

**Comment by BigD77** [comment]
Hi I still haven’t received help on why my Sync app won’t open. Any suggestions?
Thank you,

Darren

**Comment by XJWX89** [comment]
hi @BigD77, I just asked the support team to resend the email. If you do not see the email in your inbox, please check your junk mail.

**Comment by BigD77** [comment]
I replied but I am not getting an answer. When I in put my keystore it says invalid. I my be inputting it wrong so I need assistance,
Thank you

Darren
