### ISSUE TITLE
VTHO Stuck in Sync Wallet - Unable to Transfer due to Drop Down Menu stuck on VET

### ISSUE THREAD

**Issue by boochdog** [vechain/thor-sync.electron#496]
**Describe the bug**
Hi - Apparently, I am not able to transfer my VTHO holdings out of the Sync local wallet.  When going through the normal "Transfer" prompt, the only option to transfer is VET, not VTHO.  

I was able to move my VET to my cold wallet, but am not able to do so with the VTHO.  It is just locked in the local Sync wallet.  I find this ridiculous as this is Vechain's proprietary desk top app.  I went with the desk top version to ensure a fluid wallet experience over their Thor app.  I am shocked to see this be an issue. 

Is anyone else having this problem?  Sync/Vechain, can you guys help?  Please see screen capture below.  The circled "VET" area is not able to be changed to VTHO.  My VTHO at the top is essentially trapped in this wallet until this issue can be corrected. 

<img width="493" alt="Vechain Wallet" src="https://user-images.githubusercontent.com/90349731/132573384-b111aa31-d67f-4f3d-92ad-b8c816b29245.PNG">

**To Reproduce**
I am not sure how to recreate this.  It seems to be inherent to the software.  I am shocked if no one else has come across this problem or how it has been resolved if so.  I see a recent post from 8 days ago (Sept 1st, 2021) with someone having the same issue. 

**Actual result:**
Please add screenshots if needed

**Expected result:**
Sync should fix this crap immediately!  Provide a drop down option to select VTHO.  Trying to transfer the VTHO out as VET doesn't work either. 

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**
Sync v1.3.0 / Connex v1.4.2

**Additional context**
I came across this problem while transferring my VET/VTHO to a cold wallet, Ledger Nano X.  The VET transferred just fine, but without the drop down to change from VET to VTHO, it appears my VTHO is stuck! 

Also, Ledger spazzed out while creating my cold wallet and set up FIVE wallet addresses somehow - I have no clue why or how this happened and not sure if related or if this is an entirely separate issue with Ledger.  Why is this shit made so difficult?  See Screen Shot below.

IT WOULD BE GREAT IF VECHAIN WORKED WITH LEDGER TO MAKE TRANSFERS AS EASY AS THE OTHER CRYPTOS/APPS I HOLD!  Algorand was super simple.

<img width="623" alt="Sync Version" src="https://user-images.githubusercontent.com/90349731/132574815-ec867be7-37d3-43f5-a04c-bfdd55438adb.PNG">

<img width="743" alt="5 Wallets" src="https://user-images.githubusercontent.com/90349731/132574729-64d5b829-36d3-413e-8f14-8e3c02ff70a2.PNG">

**Comment by XJWX89** [comment]
duplicate issue(#494 )

**Comment by boochdog** [comment]
This is not a duplicate issue.  This issue is still active.  There was no resolution to #494, the recommendation provided did not answer the question that I have outlined in more detail in #496. 

Is there any way to get the VTHO unstuck from this wallet?  Are the creators of Sync actively working to improve/update the wallet or is it a stagnant wallet/software team?
