### ISSUE TITLE
Returning Solidity structs

### ISSUE THREAD

**Issue by silentlight** [vechain/thor-sync.electron#499]
**Describe the bug**
We noticed that when our smart contract returns structs from view functions it fails on Sync but it works just fine on the browser

**To Reproduce**
1. Create a struct in your smart contract
2. Create a function which returns struct or array of structs
3. Use it with connex in your dapp

**Actual result:**

I receive array with no element.

<img width="526" alt="Screenshot 2021-10-09 at 23 33 38" src="https://user-images.githubusercontent.com/1480637/136674240-e2b7b466-765f-416a-b123-e1406986b803.png">

**Expected result:**

I receive array with price, from, createdAt properties.
 
<img width="500" alt="Screenshot 2021-10-09 at 23 34 50" src="https://user-images.githubusercontent.com/1480637/136674257-0dea2910-3041-4f92-becc-be6708d961c9.png">

**Desktop OS :**
MacOS 10.15.7

**Sync Version:**

![image](https://user-images.githubusercontent.com/1480637/136674311-c472af32-a566-400a-8f84-049ad6e33df0.png)

**Additional context**
In our web app we are using `"@vechain/connex": "^2.0.5"`. I see that Sync browser is using version 1.4.2.
Bumping version of connex packages to the newest one might fix this issue.

**Comment by libotony** [comment]
Fixed in [v1.3.1](https://github.com/vechain/thor-sync.electron/releases/tag/v1.3.1)
