### ISSUE TITLE
Can't open any react based app in sync 1

### ISSUE THREAD

**Issue by xCodeR01** [vechain/thor-sync.electron#512]
**Describe the bug**
I have a dapp written in react that is connected to vechain using connex. I want the users to connect their wallet so that they can use our services (website is not complete yet). I could not open any react app in sync 1 and i couldn't find any other issue on this repo regarding this.

**To Reproduce**
1. Open Sync 1 wallet and go to 'https://exoworlds.io/
2. The page loads but shows no content of the website.

**Actual result:**
No website shown after going to the url and loading the page. The website is loaded for a moment but then white page apperas with no content.

**Expected result:**
Home page of exoworlds should have been displayed with information about the project (open url in regular browser to see actual page)

**Desktop OS :**
 Win10

**Sync Version:**
sync v.1.3.1

**Comment by xCodeR01** [comment]
Issue have been resolved. It was due to `undefined` value for `globalThis` in sync 1 browser, which is a standard way to access global object in modern browsers. So, if someone else faces this issue, try defining this in your app code `window.globalThis = window`.

**Comment by AsbertMa** [comment]
> Issue have been resolved. It was due to `undefined` value for `globalThis` in sync 1 browser, which is a standard way to access global object in modern browsers. So, if someone else faces this issue, try defining this in your app code `window.globalThis = window`.

You'd better check it first. @xCodeR01 
`window.globalThis ? '' : window.globalThis = window`
or
`window.connex && (window.globalThis = window)`
