### ISSUE TITLE
Transaction missing (tokens didn't show up after transfer from Binance to Sync wallet)

### ISSUE THREAD

**Issue by rtsnv** [vechain/thor-sync.electron#530]
**A transaction I made has not been recieved in my Sync wallet**
I made a transaction from my Vechain wallet on Binance which was not received in my wallet on the Ledger/Sync.

This is the transaction and while it says it has been successful, I don't see my VETs in my wallet after the transfer and it has been a while now:

https://bscscan.com/token/0x6fdcdfef7c496407ccb0cec90f9c5aaa1cc8d888?a=0x71f90d3db0710ba9d91fa34018e0409ea2b4ff29

I'm using VeChain Sync
v1.3.1 on MacOs.

A bit worried as to what happened and any help will be quite useful. Thank you in advace

**Comment by rtsnv** [comment]
I did a ton of digging last night and found out the issue is due to the fact I have used the BSC network, instead of the Vechain network. The issue is on me, but I will appreciate if you could help me resolve this. 

I spoke with Binance and they can't do much since the transaction passed through the blockchain and was [confirmed](https://bscscan.com/tx/0x564be46e465bf821112fe1e00443ed6e141cdc91551e3b29fc7274fb5c5641c9), so think you are my only option of keeping my tokens really. 

So two questions:

1. Is there any way you can recognize the tokens in my Sync wallet (0x71f90d3DB0710bA9D91Fa34018e0409EA2B4Ff29) and/or revert the transaction back to my Binance wallet where they originally came from? 

2. If the answer to the above is No, I have found an article on how to recover such tokens through a Trust Wallet and followed all the steps which helped me see my tokens. However I am unable to verify that I am the owner of the wallet and transfer them out, and I realize it might be because I don't know how to properly export my Sync Ledger VET wallet on to another platform (Trust Wallet in this case). I have my Ledger secret phrase but for some reason they still say my wallet is in a watch-only mode, meaning they can't verify it's mine. Tried to find resources on exporting Sync VET wallets and couldn't find anything useful.

Any chance you can help me with the above?
Thanks

**Comment by libotony** [comment]
@rtsnv Q1: No,since your token is in BSC net not in VeChain

**Comment by libotony** [comment]
The BSC wallet, as far as I know you could use `TrustWallet` or `MetaMask`.

The guide: https://community.trustwallet.com/t/how-to-recover-funds-sent-to-a-wrong-public-address/145

**Comment by libotony** [comment]
Here is my suggestion:
1. Go to https://github.com/iancoleman/bip39/releases and download it to your computer, run it locally and **make your computer offline when you input your recovery seeds**.
2. Step 3, select VET
3. **Take good care of your private key, anyone got it can move your funds**
4. I would suggest creating a new account and moving your fund there, if possible. And do not forget your tokens and NFTs.

**Comment by rtsnv** [comment]
Hey, thanks so much for all the tips. For some reason, I just can't seem to import my wallet to Trust. I'm just wondering if I'm using the right phrases - do you know if I should import the 24 phrases that I have for my Ledger device? I'm pretty sure I don't have a separate list of phrases for my Sync wallets only. 
The other question (and I realize it might be a bit silly to someone senior in that theme, but a bit desperate here lol), when I insert the Private Key, am I not supposed to also insert the wallet address that I have sent the tokens to? Acc to the instructions, it says the first derived address should be the right one, but I'm only seeing my tokens in the Trust wallet once I actually insert the original address (my Ledger Sync Vet wallet) and was thinking the Private Key would just give me the right to operate with that wallet/address.

**Comment by libotony** [comment]
>  when I insert the Private Key, am I not supposed to also insert the wallet address that I have sent the tokens to? 

No need to. The address is derived from the private key.

**Comment by libotony** [comment]
> Hey, thanks so much for all the tips. For some reason, I just can't seem to import my wallet to Trust. I'm just wondering if I'm using the right phrases - do you know if I should import the 24 phrases that I have for my Ledger device? I'm pretty sure I don't have a separate list of phrases for my Sync wallets only.

Use the 24 phrases of your VeChain wallet to derive the private key to your address and import it to a wallet that supports BSC.

**Comment by libotony** [comment]
> So it should match, i.e. be 0x71f90d3DB0710bA9D91Fa34018e0409EA2B4Ff29 ?

Yes, and in Section 4 you will see the address.

**Comment by rtsnv** [comment]
> > Hey, thanks so much for all the tips. For some reason, I just can't seem to import my wallet to Trust. I'm just wondering if I'm using the right phrases - do you know if I should import the 24 phrases that I have for my Ledger device? I'm pretty sure I don't have a separate list of phrases for my Sync wallets only.
> 
> Use the 24 phrases of your VeChain wallet to derive the private key to your address and import it to a wallet that supports BSC.

I'm pretty sure that, since I created the Sync wallet on my Ledger Nano, I don't have a separate list of phrases? Or am I wrong............... :(

**Comment by rtsnv** [comment]
OK, that's what I'm doing. Cool, so that must work. 

OK, i'll spend another few hours later today and give it a shot.

I'll report asap.

Thanks for being patient, I appreciate this!

**Comment by rtsnv** [comment]
Just carefully went through all steps again and completed **successfully**! I can't thank you enough man, seriously. Hope this serves as a reference to everyone in the same situation going forward and you got a VET fan for life :) Cheers
