### ISSUE TITLE
Cant W/D VThor - VeChain Wallet Error Invalid data received (0x6a80) 

### ISSUE THREAD

**Issue by SemperFi84** [vechain/thor-sync.electron#535]
Tried everything to move VThor not sure what to do.  Help please.  Using Ledger VeChain can be moved w/o issue.

**Comment by XJWX89** [comment]
hi @SemperFi84 , 
**For Ledger device: INCORRECT_DATA (0x6a80).**

please enable below settings on your ledger device.

   - In VeChain App Setting ,set **Contract data** to **Yes**
   - In VeChain App Setting ,set **Multi-clause** to **Yes**
 
 I will now close this issue, but please feel free to reopen it if you have any further questions or concerns.
