### ISSUE TITLE
unable to withdraw VTHO due to error 0x6e80

### ISSUE THREAD

**Issue by eunia12345** [vechain/thor-sync.electron#539]
**Describe the bug**
Provide a brief description of the issue

After struggling to withdraw VTHO from the Sync app. I decided to use MyToken. I am able ot withdraw however after connecting the ledger and accepting it I am getting the following error code. 0x6e80

**To Reproduce**
1. Go to My Token
2. Enter Binance adress
3. click send
4. connect with the ledger 
5. error message

**Actual result:**
Please add screenshots if needed

**Expected result:**

**Desktop OS :**
 Win10/MacOS 10.14.2/.....

**Sync Version:**
syn and syn 2.0 none allow me to withdraw VTHO. Only allow me to withdraw VET (which I do not have)

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue
![Screenshot 2022-10-07 123826](https://user-images.githubusercontent.com/115227542/194544735-b696bba2-8f1c-49e3-a3b1-65455c21e49d.jpg)

**Comment by XJWX89** [comment]
hi @eunia12345 , please connect your Ledger device and navigate to VeChain app.

1. In VeChain App Setting ,set ***Contract data*** to **Yes**
1. In VeChain App Setting ,set ***Multi-clause*** to **Yes**

**Comment by eunia12345** [comment]
Hi where is VeChain App settings? Is it in Ledger or Sync?

**Comment by eunia12345** [comment]
![vechain setting prnt screen](https://user-images.githubusercontent.com/115227542/195039844-1b341cd8-3d0c-454e-b392-43634604e689.jpg)


there is no coontract data here?

**Comment by XJWX89** [comment]
> Hi where is VeChain App settings? Is it in Ledger or Sync?

its in the ledger device. 
1. Connect your ledger device 
2. Navaigate to Vechain app and launch the app.
3. Navigate to Settings 
4. In VeChain App Setting , set the `Contract data ` & `Multi-clause` to ***YES***

**Comment by eunia12345** [comment]
Thank you that has worked I managed to send it out.
