### ISSUE TITLE
Can't transfer out from Sync w/ Ledger

### ISSUE THREAD

**Issue by ukiyazero** [vechain/thor-sync.electron#545]
I tried to withdraw from Sync w/ Ledger to Crypto.com as a test and it keeps failing, I updated the priority and same result, error is "Dropped"

**Desktop OS :**
 Win11

**Sync Version:**
1.3.2

**Comment by XJWX89** [comment]
hi @ukiyazero ,  Please make sure you have enough VTHO before sending the transaction.

**Comment by ukiyazero** [comment]
my bad, I just realized its using VTHO for gas/transaction fees not VET, case close, thanks for the help @XJWX89
