### ISSUE TITLE
my vet not arriving on Trustwallet?

### ISSUE THREAD

**Issue by Regalis75** [vechain/thor-sync.electron#549]
my vet not arriving on Trustwallet?
What I have done wrong.
This is my Trsuwallet address for VET :0xe587FB13A7ffc01D08dE3Dd3DE9E2c33fB1da6e9
my vet not arriving on Trustwallet?
What I have done wrong.
This is my Trsuwallet address for VET :0xe587FB13A7ffc01D08dE3Dd3DE9E2c33fB1da6e9

Are my vets gone now? :-(

**Comment by SUPPORTTEAMHERR** [comment]
> my vet not arriving on Trustwallet? What I have done wrong. This is my Trsuwallet address for VET :0xe587FB13A7ffc01D08dE3Dd3DE9E2c33fB1da6e9 my vet not arriving on Trustwallet? What I have done wrong. This is my Trsuwallet address for VET :0xe587FB13A7ffc01D08dE3Dd3DE9E2c33fB1da6e9
> 
> Are my vets gone now? :-(

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Usernamethoma** [comment]
@Regalis75 We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Helpcentera** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Chukwulawrence** [comment]
@Regalis75 We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5

**Comment by XJWX89** [comment]
Hello @Regalis75 , regarding questions related to wallets/assets, as they involve personal privacy and confidentiality, please send your inquiry to [support@vechain.com](mailto:support@vechain.com). Support team will assist you with your issue.
