### ISSUE TITLE
VET Transfer Issue

### ISSUE THREAD

**Issue by PhilippT93** [vechain/thor-sync.electron#551]
I sent VET from Crypto.com to Sync. Correct address but the amounts never showed on Sync.

**To Reproduce**
2. 
3. 
4.

**Actual result:**
Please add screenshots if needed

**Expected result:**

**Desktop OS :**

**Sync Version:**

**Additional context**
Any additional information, related issues, screenshots, or transaction details that might be necessary to reproduce the issue

**Comment by XJWX89** [comment]
Hello @PhilippT93 , regarding questions related to wallets/assets, as they involve personal privacy and confidentiality, please send your inquiry to [support@vechain.com](mailto:support@vechain.com). Support team will assist you with your issue.
