### ISSUE TITLE
HELP ME!! Ankr to Sync

### ISSUE THREAD

**Issue by Distablished** [vechain/thor-sync.electron#555]
Ive send ANKR from Bitvavo (crypto brooker) To my Sync wallet but it hasnt shown up yet!
Can some one help me ?

**Comment by XJWX89** [comment]
Hello @Distablished , regarding questions related to wallets/assets, as they involve personal privacy and confidentiality, please send your inquiry to [support@vechain.com](mailto:support@vechain.com). Support team will assist you with your issue.
