### ISSUE TITLE
recovering wallets

### ISSUE THREAD

**Issue by gcynthia123** [vechain/thor-sync.electron#561]
I am having trouble recovering wallets. i don't have mnemonic phrases. have wallet addresses.  not accepting.

**Comment by gcynthia123** [comment]
The wallets were on connex sync.

**Comment by gcynthia123** [comment]
I only had phrases for one wallet and recovered that.  They used to all appear when I opened the wallet, and I don't believe the first two had phrases.  Can data recovery work, why did the disappear?

**Comment by FredKemp1** [comment]
> I am having trouble recovering wallets. i don't have mnemonic phrases. have wallet addresses.  not accepting. 

Hello, I am a cybersecurity engineer and ethical hacker with an emphasis in account recoveries. I can handle this project. Please contact me for further details.

**Comment by gcynthia123** [comment]
Thank you for response.  Fortunately they reappeared and I could access them!!


Sent from Yahoo Mail for iPad


On Friday, February 17, 2023, 7:16 AM, FredKemp1 ***@***.***> wrote:





I am having trouble recovering wallets. i don't have mnemonic phrases. have wallet addresses. not accepting.


Hello, I am a cybersecurity engineer and ethical hacker with an emphasis in account recoveries. I can handle this project. Please contact me for further details.

**Comment by XJWX89** [comment]
I'm glad that your issue has been resolved. I will now close this issue, but please feel free to reopen it if you have any further questions or concerns.
