### ISSUE TITLE
Recover vechain.

### ISSUE THREAD

**Issue by uvconnects** [vechain/thor-sync.electron#571]
**Describe the bug**
Provide a brief description of the issue
I wrote down my 12 word password. type it in. when trying to recover it will not recover. I done this many times before this never happen. it will not recover my vechain. 
**To Reproduce**
1. [Go to '...'](https://explore.vechain.org/accounts/0xae647de1e6f905bf5161cf4bcb93031702977cfe/txs)

**Actual result:**
Please add screenshots if needed

**Expected result:**
how can i recover my vechain.

**Desktop OS :**
 Win10/MacOS 10.14.2/.....
windows 11

**Sync Version:**
sync version 2 and 1. 

**Additional context**
Any additional information, related issues, screenshots, transaction details that might be necessary to reproduce the issue
When I open my sync said it had to update. it did and thats when it was not showing.  I can send my 12 password.

**Comment by Trezor-29Mod1** [comment]
@uvconnects It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptorectifications.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
