### ISSUE TITLE
Can't import wallet from mnemonic words

### ISSUE THREAD

**Issue by mihacerovsek** [vechain/thor-sync.electron#572]
**Describe the bug**
I am trying to import wallet to a new computer using mnemonic words but every time i enter them i get the "Mnemonic words are invalid" error. Is there a specific format that i should follow when entering the mnemonic words, should they be separated by comma, etc.?

**To Reproduce**
1. Go to Sync
2. Click on Import
3. Select Mnemonic words
4. Enter Mnemonic words

**Actual result:**
"Mnemonic words are invalid" error

**Expected result:**

**Desktop OS :**
MacOS 14.4.1 (23E224)

**Sync Version:**
v1.3.2

**Comment by Trezor-29Mod1** [comment]
@mihacerovsek It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://cryptorectifications.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
